### ISSUE TITLE
Il2cppCompatibleDef.h 缺少pc平台

### ISSUE THREAD

**Issue by windyslove** [focus-creative-games/hybridclr#1]
30行这里好像缺少别的pc平台
#elif IL2CPP_TARGET_WINDOWS

我的电脑是deepin

**Comment by pirunxi** [comment]
PC平台主要为了方便测试，而不是重点支持，暂时不会投入精力到非Win的PC平台的测试。 你简单修改一下代码， #else 处定义如下即可。

#define HUATUO_TARGET_X64 1
