### ISSUE TITLE
4.0.3 打开增量GC unity2021.3.30 报NotSupportNative2Managed 相同代码3.4.2没问题

### ISSUE THREAD

**Issue by iamnewaplayer** [focus-creative-games/hybridclr#101]
Unity Editor版本。如 2021.3.30
操作系统。 Win 10
出错的BuildTarget：Win64
com.code-philosophy.hybridclr的版本号。4.03

遇到'ExecutionEngineException: NotSupportNative2Managed'
已反复重新Generate/All 无效

报错代码涉及到的 泛型
Dictionary<int, FieldInfo>
List<FieldInfo> sort
Dictionary<string, List<FieldInfo>> FieldSorts

项目中 是下面这个函数报的错

        public static List<FieldInfo> Sorts(Type tt)
        {
            if (!FieldSorts.ContainsKey(tt.Name))
            {
                Dictionary<int, FieldInfo> fieldSorttemp = new Dictionary<int, FieldInfo>();
                List<FieldInfo> sort = new List<FieldInfo>();

                foreach (var field in tt.GetFields())
                {
                    var fieldAttr = field.GetCustomAttributes(typeof(FieldSortAttribute), false);
                    foreach (var attr in fieldAttr)
                    {
                        if (attr is FieldSortAttribute)
                        {
                            FieldSortAttribute fieldSortAttribute = (FieldSortAttribute)attr;
                            fieldSorttemp[fieldSortAttribute.FieldSort] = field;
                        }
                    }
                }

                Dictionary<int, FieldInfo> SortedByKey =
                    fieldSorttemp.OrderBy(p => p.Key).ToDictionary(p => p.Key, o => o.Value);

                foreach (var value in SortedByKey.Values)
                {
                    sort.Add(value);
                }

                FieldSorts[tt.Name] = sort;
            }

            return FieldSorts[tt.Name];
        }

**Comment by pirunxi** [comment]
按要求给基于hybridclr_trial的可复现工程

**Comment by pirunxi** [comment]
我们使用以上代码，在trial及我们单元测试项目上都没有复现出问题。由于已经严重浪费了我们的时间，如再想反馈，只能付费联系商务。
