### ISSUE TITLE
昨天提的4.0.3 打开增量GC 报NotSupportNative2Managed 今天找到了更具体的问题 但我搞了个demo却无法重现

### ISSUE THREAD

**Issue by iamnewaplayer** [focus-creative-games/hybridclr#102]
昨天的代码中有一句
Dictionary<int, FieldInfo> SortedByKey = fieldSorttemp.OrderBy(p => p.Key).ToDictionary(p => p.Key, o => o.Value);
报NotSupportNative2Managed  是这句报的
我把相关代码放到一个新的demo中测试 缺不报错

自己的项目我现在把他改写不用Linq 则不报错了 不知道为什么

**Comment by pirunxi** [comment]
这个问题在 v4.0.7版本修复了
