### ISSUE TITLE
项目中使用DOST，用到了IComponentData组件，在通过EntityManager创建一个Entity的时候，报错。

### ISSUE THREAD

**Issue by doyoframework** [focus-creative-games/hybridclr#105]
项目中使用DOST，用到了IComponentData组件，在通过EntityManager创建一个Entity的时候报错了

EntityManager manager = World.DefaultGameObjectInjectionWorld.EntityManager;
manager.CreateEntity(typeof(DisplayObject));

错误如下：
ArgumentException: Unknown Type:`DOST.Component.DisplayObject` All ComponentType must be known at compile time. For generic components, each concrete type must be registered with [RegisterGenericComponentType].

不过，在编辑器模式下运行是没有问题的，打包成Windows64的exe应用程序，运行就会出现这个错误。

DisplayObject的代码：

public struct DisplayObject : IComponentData, IQueryTypeParameter
{
    public float Value;
}

使用的
HybridCLR 4.0.4
Unity 2022.3.4f1c1
Entities 1.0.14
Entities Graphics 1.0.14

**Comment by pirunxi** [comment]
dots要求那些组件都提交注册好了。不清楚dots是否支持手动注册，如果支持的话，可以加载热更新dll后自己注册；如果不支持，意味着你必须将那些组件都放到aot里，或者自己改dots源码。

**Comment by doyoframework** [comment]
> dots要求那些组件都提交注册好了。不清楚dots是否支持手动注册，如果支持的话，可以加载热更新dll后自己注册；如果不支持，意味着你必须将那些组件都放到aot里，或者自己改dots源码。

目前的问题是，在Editor模式下，运行是正常的，Build出一个Windows的exe项目运行时，出现这个错误，我把相关的元数据都补充了，但是错误依然存在，如您所说，我需要手动注册，我不太理解如何手动注册-_-

**Comment by doyoframework** [comment]
这就算关闭了？这算哪门子解决啊..

**Comment by lixianmin** [comment]
这是不太支持DOTS么? 话说DOTS天天变也是够烦人的哈哈

**Comment by TapsJoy** [comment]
dots别热更啊，性能不好。

**Comment by pirunxi** [comment]
> 这就算关闭了？这算哪门子解决啊..

这不是我们当前重点要关注的问题。但会在后面解决。你要是想听到详细的技术分析和解答，并且想现在解决，联系我们公司商务，付费解决。

**Comment by pirunxi** [comment]
我们现在已经解决了这个问题。商业化版本已经支持绝大多数dots特性，具体见 https://hybridclr.doc.code-philosophy.com/docs/business/dots
