### ISSUE TITLE
unity 2022.3.10lts unity 2021.3.28f1 导入插件就崩溃

### ISSUE THREAD

**Issue by woowloop** [focus-creative-games/hybridclr#108]
如题 只要一接入插件 就蹦。unity 2020.3.x测试没有问题。从2020升级到2021立马就崩溃。
=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Object:wrapper_native_000001852DC05290 <0x0012c>
	  at MonoHook.HookUtils:FlushICache <0x00108>
	  at MonoHook.CodePatcher:FlushICache <0x00092>
	  at MonoHook.CodePatcher:ApplyPatch <0x00162>
	  at MonoHook.MethodHook:DoInstall <0x00342>
	  at MonoHook.MethodHook:Install <0x00162>
	  at HybridCLR.MonoHook.CopyStrippedAOTAssembliesHook:.cctor <0x0041a>
	  at System.Object:runtime_invoke_void <0x00184>
	  at <unknown> <0xffffffff>
	  at System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor <0x000c1>
	  at System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor <0x0019a>
	  at UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes <0x00652>
	  at <Module>:runtime_invoke_void_object <0x0018a>
=================================================================

**Comment by pirunxi** [comment]
Win 还是 Mac? 如果是Mac, CPU是 Intel还是Silicon架构？

**Comment by woowloop** [comment]
win10 cpu是intel 双cpu 服务器主板

**Comment by woowloop** [comment]
就我电脑崩 其他人电脑没问题 可为啥2020就没问题
