### ISSUE TITLE
Exception: No such proxy method:xxx

### ISSUE THREAD

**Issue by ShenKang4181** [focus-creative-games/hybridclr#110]
使用这个插件后，出现这个问题
https://github.com/yasirkula/UnityNativeGallery/issues/300
[bug反馈，No such proxy method , 复现工程.zip](https://github.com/focus-creative-games/hybridclr/files/13049875/bug.No.such.proxy.method.zip)

**Comment by pirunxi** [comment]
复现工程不合要求。而且这个问题看起来跟hybridclr没有关系。请联系商务付费解决，

**Comment by ShenKang4181** [comment]
新建一个工程，能正常使用，导入hybridclr后，就出现这个bug了

**Comment by ShenKang4181** [comment]
Unity Editor版本。如 2020.4.48
操作系统。Win 10
出错的BuildTarget。 Android 
com.code-philosophy.hybridclr的版本号。4.0.10
截图及日志文件
Exception: No such proxy method: NativeGalleryNamespace.NGMediaReceiveCallbackAndroid.OnMediaReceived(System.String)

工程根目录有一个aaad.apk，安装后可立刻复现

打包流程：先gen/all , 点击tools/wantbuild , new一个addressables，打包

keystore 的密码是 6个a , aa , 6个a

**Comment by pirunxi** [comment]
不要用addressable，请按要求直接在trial工程上复现

**Comment by ShenKang4181** [comment]
下载了[trial](https://github.com/focus-creative-games/hybridclr_trial)后，

**Comment by ShenKang4181** [comment]
下载了[trial](https://github.com/focus-creative-games/hybridclr_trial)后，
unity 版本：2020.3.48 ， 切到了安卓平台
1.升级了hybridclr到4.0.10
2.新加https://package.openupm.cn的包：com.yasirkula.nativegallery
3.新加包：com.yasirkula.ingamedebugconsole（加这个的目的是可以看android的log，ConsoleToScreen这个自带的脚本看不到）把package/com.yasirkula.ingamedebugconsole/Plugins/IngameDebugConsole/IngameDebugConsole.prefab拖到了main场景里面
4.在HotUpdate里新建了一个脚本：aa.cs
5.HotUpdate.asmdef添加了引用nativegallery
6.把aa.cs挂到了prefabs/cube上面并新建了个button，绑定点击事件aa.cs里的方法
7.Generate/All
8.HybridCLR/Build/BuildAssetsAndCopyToStreamingAssets
9.Build Settings里打包
10.没出包，报错了，新建了一个keystore，密码6个0，alias：aa
11.重新打包，成功了  
12.安装到手机，运行，点击按钮，随便选一张图，复现了
Exception: No such proxy method: NativeGalleryNamespace.NGMediaReceiveCallbackAndroid.OnMediaReceived(System.String)

[hybridclr_trial-main.zip](https://github.com/focus-creative-games/hybridclr/files/13050923/hybridclr_trial-main.zip)

**Comment by ShenKang4181** [comment]
大概啥时候修复呢？

**Comment by pirunxi** [comment]
我们会修复它

**Comment by ShenKang4181** [comment]
想知道大概啥时候修复呢？

**Comment by ShenKang4181** [comment]
大概啥时候修复呢？

**Comment by pirunxi** [comment]
经确认，这是裁剪导致。 如此低级的bug，你不自己好好检查，却来反馈bug???

**Comment by ShenKang4181** [comment]
你凶什么，你不是也没发现吗，而且新建工程不用hybridclr就没问题啊，我去试试去
