### ISSUE TITLE
WASPlayer 平台 生成桥接函数报错

### ISSUE THREAD

**Issue by woowloop** [focus-creative-games/hybridclr#111]
Exception: no aot assembly found. please run `HybridCLR/Generate/All` or `HybridCLR/Generate/AotDlls` to generate aot dlls before runing `HybridCLR/Generate/MethodBridge`
经测试发现在CopyStrippedAOTAssemblies脚本中没有处理WASPlayer平台 导致CopyStripDlls未执行，AssembliesPostIl2CppStrip目录下为空

**Comment by pirunxi** [comment]
不可能

**Comment by woowloop** [comment]
不可能是什么玩意 这么谜之自信 麻烦睁大眼去看看代码
