### ISSUE TITLE
function signature mismatch

### ISSUE THREAD

**Issue by tangjialang** [focus-creative-games/hybridclr#114]
Unity Editor 版本:：2021.3.25f1c1
操作系统：Win 10
BuildTarget：WebGL
com.code-philosophy.hybridclr 的版本号：v4.0.12
截图：
TestFunc方法内报错截图
![bug](https://github.com/focus-creative-games/hybridclr/assets/42792101/23e2c373-ab3d-4613-b2d2-21c4f748073c)
这个是多补充了AOT元数据的截图-出现这个问题之后就一直有问题了，除非把多余补充的元数据去掉然后重新generate all：
![bug4](https://github.com/focus-creative-games/hybridclr/assets/42792101/220664ee-4782-4d48-9a86-f886274d778e)
复现条件：使用 Unity WebGL 微信小游戏适配的工具转为 微信小游戏之后 使用微信开发者工具打开就能复现
使用工程配置本地服务器，使用微信开发者工具打开，修改为本地资源服把webgl资源放入就能重现，已经把锁需要添加尽量准备好了，如果有问题可以联系我
打包补充图片：
![bug3](https://github.com/focus-creative-games/hybridclr/assets/42792101/a5f1f0f9-7533-4d94-a567-e923b90315c4)
需要把打包出来的 webgl目录下所有文件都部署到本地资源服务器，可使用的Addressables Hosting完成
部署补充图片：
![bug2](https://github.com/focus-creative-games/hybridclr/assets/42792101/9b7986a4-c36a-489b-847a-35d535be9f27)
出错的位置：InstantiateByAsset.cs中TestFunc方法
更新资源之后记得每次把开发者工具缓存清理下，已保证最新打包的资源被加载

**Comment by pirunxi** [comment]
对于微信小游戏平台的问题，请联系我们商务，付费解决，2000元/小时。

**Comment by pirunxi** [comment]
解决就好。这个问题在常见错误中早有说明。
