### ISSUE TITLE
开启nullable选项报错的问题

### ISSUE THREAD

**Issue by AioiMio** [focus-creative-games/hybridclr#116]
Unity Editor版本：2022.3.13f1
操作系统: Win 11
com.code-philosophy.hybridclr的版本号: v4.0.13

 在Unity的Project Settings - Player - Other Settings - Additional Compiler Arguments中输入 -nullable:enable 之后，Editor报错
![image](https://github.com/focus-creative-games/hybridclr/assets/99109496/79569711-8196-486e-bfe3-8d0b4ef52142)

出错的c#代码位置: com.code-philosophy.hybridclr/Editor/Settings/ScriptableSignleton.cs第61行
![image](https://github.com/focus-creative-games/hybridclr/assets/99109496/19c445ab-5651-4bcc-adf5-dda050e4dafd)

请问之后有支持nullable的计划吗？

**Comment by pirunxi** [comment]
看样子关系不大，我们复查一下

**Comment by pirunxi** [comment]
我们已经修复了这个问题，下个版本会包含这个修复。感谢。
