### ISSUE TITLE
Unity 2020.3.48f1 + HybridCLR 4.0.14，在开启增量GC的情况下极大概率出现崩溃

### ISSUE THREAD

**Issue by xzhjieie** [focus-creative-games/hybridclr#117]
**Describe the bug | 描述问题**
Unity 2020.3.48f1 + HybridCLR 4.0.14，在开启增量GC的情况下极大概率出现崩溃；如果不开启增量GC，则不会出现这个问题了。后续升级版本到HybridCLR 4.0.15 后仍然存在崩溃问题。

**Enviroment | 环境**

- Unity Version: 2020.3.48f1 
-  com.code-philosophy.hybridclr Version: 4.0.14
- Platform: Android
- CPU：Arm64

**To Reproduce | 复制步骤**
C++ 层调用AOT 中的接口 OnRecvGameShowData，在切换场景后引起了崩溃。
```
// C++ 层调用该接口
[MonoPInvokeCallback(typeof(DegateOnRecvGameShowData))]
public static void OnRecvGameShowData(int iCmd, IntPtr data, int iLen)
{
    Marshal.Copy(data, abyRecvBufer, 0, iLen);
    // 利用反射调用热更 dll 里面的接口
    HotApis.GameApp_GeMain_Instance_OnRecvGameShowData(iCmd, abyRecvBufer, iLen);
}
```

**崩溃日志**
崩溃日志是这样的
![image](https://github.com/focus-creative-games/hybridclr/assets/129391960/f31c3ac1-205d-420d-8e0a-a8f1a1895eff)

这是解析后的调用堆栈日志
![image](https://github.com/focus-creative-games/hybridclr/assets/129391960/5574cbb9-3d72-4dd5-b7c3-1b6c00feb2e4)

**Comment by pirunxi** [comment]
提供可复现的工程。直接提供win visual studio工程也可以
