### ISSUE TITLE
Editor 2023.2: 找不到 UnityEditor.Il2cpp namespace

### ISSUE THREAD

**Issue by wintbiit** [focus-creative-games/hybridclr#121]
**Describe the bug | 描述问题**
编辑器报错 
`Library\PackageCache\com.code-philosophy.hybridclr@6ffb977ef3\Editor\BuildProcessors\CopyStrippedAOTAssemblies.cs(11,19): error CS0234: The type or namespace name 'Il2Cpp' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
`
`Library\PackageCache\com.code-philosophy.hybridclr@6ffb977ef3\Editor\BuildProcessors\PatchScriptingAssemblyList.cs(12,19): error CS0234: The type or namespace name 'Il2Cpp' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`

**Enviroment | 环境**
- Unity Version: 2023.2.3
-  com.code-philosophy.hybridclr Version: 5.0.0
- Platform: Win 64 Standalone

**Expected behavior | 期望的结果**
[支持的Unity版本和平台](https://hybridclr.doc.code-philosophy.com/docs/basic/supportedplatformanduniyversion#%E5%85%BC%E5%AE%B9%E7%9A%84unity%E7%89%88%E6%9C%AC) 提到2023.2.0ax （已经支持，尚未对外发布），是否稳定或可下放社区版？

**Screenshots | 截图或者日志**
![image](https://github.com/focus-creative-games/hybridclr/assets/68735689/e29f092d-72c9-4577-8710-a0f91ce30856)

**Comment by pirunxi** [comment]
目前未发布对2023的支持，等发布2023LTS后我们才会发布。
