### ISSUE TITLE
主包(win_x64 build player)用PostProcessing时启动会崩溃 

### ISSUE THREAD

**Issue by jzq740176597** [focus-creative-games/hybridclr#127]
**Describe the bug | 描述问题**

主包(win_x64 build player)用PostProcessing时启动会崩溃 

** Enviroment | 环境 **

- Unity Version: 2021.3.27f1
- -  com.code-philosophy.hybridclr Version: 5.1.0
- Platform: Win 64 Standalone

**To Reproduce | 复制步骤 **

Please provide a reproduction project. Please try to reproduce this bug on the https://github.com/focus-creative-games/hybridclr_trial project. | 提供复现工程，请尽量在 https://github.com/focus-creative-games/hybridclr_trial 项目上复现这个bug。

[https://gitee.com/megajia/PureHybirdClrTest.git](url) <master branch>

Steps to reproduce the behavior :
1. build x64 player
2. run it

**Expected behavior | 期望的结果**
正常运行

**Screenshots | 截图或者日志**

![image](https://github.com/focus-creative-games/hybridclr/assets/1163977/28fe92e7-fd00-47c8-a217-0162f17309a8)

**Additional context | 补充信息**

o	Win 64可复现的导出Debug工程, 比较大, 上面unity工程可以直接生成

**Comment by pirunxi** [comment]
已修复，下个版本会包含这个修复
