### ISSUE TITLE
win-x64 player  启动直接闪退 (Build时 HybirdClr 已关闭)

### ISSUE THREAD

**Issue by jzq740176597** [focus-creative-games/hybridclr#129]
**Describe the bug | 描述问题**
See title

** Enviroment | 环境 **

- Unity Version: 2021.3.27f1
-  com.code-philosophy.hybridclr Version: 5.10 (修复Post_processing - BUG 版)
- Platform: Win 64 Standalone

**To Reproduce | 复制步骤 **

有Build 版exe, 直接运行即可重现

**Expected behavior | 期望的结果**
正常运行

**Screenshots | 截图或者日志**
 闪退 (Player.log 截图)

![1](https://github.com/focus-creative-games/hybridclr/assets/1163977/385b1078-e77a-491a-b8d9-168369b125c3)

**Additional context | 补充信息**

**Comment by pirunxi** [comment]
5.2.0版本已经修复此问题
