### ISSUE TITLE
Unity2021.3.1f1 打包WebGL报错，undefined symbol: _ZN14RefcountedData7ReleaseEv 

### ISSUE THREAD

**Issue by skyhe1410** [focus-creative-games/hybridclr#13]

**Comment by pirunxi** [comment]
这是跟hybridclr无关。 是WebGL的限制，你用了一些它不支持api。

**Comment by skyhe1410** [comment]
我什么代码都没写，用的是官方例子工程打包

**Comment by skyhe1410** [comment]
> 这是跟hybridclr无关。 是WebGL的限制，你用了一些它不支持api。

我什么代码都没写，用的是官方例子工程打包

**Comment by pirunxi** [comment]
官方的例子也不能在WebGL下跑。 你先去掉HybridCLR跑通一个项目，再接入HybridCLR.

**Comment by skyhe1410** [comment]
> 

但是官方例子在Unity2020.3.21版本下打包就没问题，只是在2021.3.1f1下打包就报上面这个错

**Comment by skyhe1410** [comment]
> 官方的例子也不能在WebGL下跑。 你先去掉HybridCLR跑通一个项目，再接入HybridCLR.

但是官方例子在Unity2020.3.21版本下打包就没问题，运行也没问题，只是在2021.3.1f1下打包就报上面这个错
