### ISSUE TITLE
 The type or namespace name 'HybridCLR' could not be found

### ISSUE THREAD

**Issue by Study123Guangen** [focus-creative-games/hybridclr#130]
**Describe the bug | 描述问题**
Assets\LoadDll.cs(1,7): error CS0246: The type or namespace name 'HybridCLR' could not be found (are you missing a using directive or an assembly reference?)

** Enviroment | 环境 **

- Unity Version: 2021.3.16
-  com.code-philosophy.hybridclr Version: 5.2.1
- Platform: Win 64 Standalone...

**To Reproduce | 复制步骤 **
加载热更新程序集
为了简化演示，我们不通过http服务器下载HotUpdate.dll，而是直接将HotUpdate.dll放到StreamingAssets目录下。

HybridCLR是原生运行时实现，因此调用Assembly Assembly.Load(byte[])即可加载热更新程序集。

创建Assets/LoadDll.cs脚本，然后在main场景中创建一个GameObject对象，挂载LoadDll脚本。

做到這邊的時候將程式碼貼上以後
using HybridCLR;
這一行就有問題了，請問我應該如何解決

**Comment by pirunxi** [comment]
你没安装 HybridCLR package。按照 [安装文档](https://hybridclr.doc.code-philosophy.com/docs/basic/install) 说明做。 如果你确实已经安装了HybridCLR，说明LoadDll脚本并不在全局的Assembly-CSharp里，而是在你的某个assembly definition里。给这个assembly definition 加上 HybridCLR.Runtime模块的引用即可。还有问题去新手群或discord问题， 主页README里有地址

**Comment by Study123Guangen** [comment]
不好意思 我在Readme裡面只有看到官網，沒有看到新手群和discord可以請您跟我說在哪裡麻，謝謝!

**Comment by Bian-Sh** [comment]
> 不好意思 我在Readme裡面只有看到官網，沒有看到新手群和discord可以請您跟我說在哪裡麻，謝謝!
qq:680274677

**Comment by Study123Guangen** [comment]
不好意思 我沒有QQ 請問有Discord麻

**Comment by pirunxi** [comment]
readme里有 https://discord.gg/BATfNfJnm2

**Comment by Study123Guangen** [comment]
謝謝!!

**Comment by LightYourStar** [comment]
如果你是按照教程做的，并且确保在HybridCLR中 Install过了，检查下你创建的HotUpdate程序集，是不是没放到HotUpdate目录内，直接放到Assets下面了，如果是，那么你所创建的所有C#文件都会归为HotUpdate程序集，而不是默认的CSharp程序集，而CSharp程序集是可以自动引用所有的自定义程序集
