### ISSUE TITLE
HybridCLRSettings的hotUpdateAssemblies，hotUpdateAssemblyDefinitions 被清空

### ISSUE THREAD

**Issue by wwanstudio** [focus-creative-games/hybridclr#132]
**Describe the bug | 描述问题**

** Enviroment | 环境 **

- Unity Version: 2021.3.29
- Unity Version: 2022.3.20
- 
-  com.code-philosophy.hybridclr Version: 5.2.1
- Platform: Win 64 Standalone|Android|iOS| ...

**To Reproduce | 复制步骤 **

Steps to reproduce the behavior :
1.设置热更新需要的【hotUpdateAssemblyDefinitions】
 ![设置1](https://github.com/focus-creative-games/hybridclr/assets/2221845/ee17b6ae-9aec-44c5-912c-4e3cbbb1003f)

2. 运行编译apk，或者 exe
3.【hotUpdateAssemblyDefinitions】被清空
 ![设置2](https://github.com/focus-creative-games/hybridclr/assets/2221845/fe570ef9-9f74-4131-882e-ccbefcb6fadf)

**Comment by pirunxi** [comment]
能给一个工程吗
