### ISSUE TITLE
堆栈

### ISSUE THREAD

**Issue by SendSi** [focus-creative-games/hybridclr#136]
Unity 打包出来的apk,看不Debug.LogError的输出的堆栈调用信息,怎么解决

**Comment by pirunxi** [comment]
我们测试是有的。如果没有，请bug反馈模板要求提供复现工程，发给 商业技术支持QQ

**Comment by pirunxi** [comment]
我们测试是有的。如果没有，请bug反馈模板要求提供复现工程，发给 商业技术支持QQ

**Comment by pirunxi** [comment]
我们测试是有的。如果没有，请bug反馈模板要求提供复现工程，发给 商业技术支持QQ

**Comment by pirunxi** [comment]
至少从v4.0.0版本起肯定是有堆栈的。如果有问题请联系我们技术支持。
