### ISSUE TITLE
linux unity6000 不能启动

### ISSUE THREAD

**Issue by windyslove** [focus-creative-games/hybridclr#138]
**Describe the bug | 描述问题**
openkylin使用unity 6000.0.10f1c1 打包linux平台不能启动

** Enviroment | 环境 **系统下
- 操作系统: openkylin 2.0 (nile) ，Linux  6.6.0-1-generic 

- Unity Version:  6000.0.10f1c1 (0d20b9198bf0)
-  com.code-philosophy.hybridclr Version: v6.4.0
- Platform: linux x86_64

**To Reproduce | 复制步骤 **
使用官方教程项目直接打包运行
 https://github.com/focus-creative-games/hybridclr_trial

Steps to reproduce the behavior :
1. 执行 HybridCLR / GenerateALL
2. 执行 Build / BuildAssetsAndCopyToStreammingAssets
3. 执行 File / Build And Run
4. 运行可执行程序

**Expected behavior | 期望的结果**
正常打开程序

**Screenshots | 截图或者日志**
<details>
<summary>终端运行输出</summary>
/media/DATA/WorkSpaceDemo/hybridclr_trial/Build$ ./hybridclr_trail.x86_64 </br>
[UnityMemory] Configuration Parameters - Can be set up in boot.config</br>
"memorysetup-bucket-allocator-granularity=16"</br>
"memorysetup-bucket-allocator-bucket-count=8"</br>
"memorysetup-bucket-allocator-block-size=4194304"</br>
"memorysetup-bucket-allocator-block-count=1"</br>
"memorysetup-main-allocator-block-size=16777216"</br>
"memorysetup-thread-allocator-block-size=16777216"</br>
"memorysetup-gfx-main-allocator-block-size=16777216"</br>
"memorysetup-gfx-thread-allocator-block-size=16777216"</br>
"memorysetup-cache-allocator-block-size=4194304"</br>
"memorysetup-typetree-allocator-block-size=2097152"</br>
"memorysetup-profiler-bucket-allocator-granularity=16"</br>
"memorysetup-profiler-bucket-allocator-bucket-count=8"</br>
"memorysetup-profiler-bucket-allocator-block-size=4194304"</br>
"memorysetup-profiler-bucket-allocator-block-count=1"</br>
"memorysetup-profiler-allocator-block-size=16777216"</br>
"memorysetup-profiler-editor-allocator-block-size=1048576"</br>
"memorysetup-temp-allocator-size-main=4194304"</br>
"memorysetup-job-temp-allocator-block-size=2097152"</br>
"memorysetup-job-temp-allocator-block-size-background=1048576"</br>
"memorysetup-job-temp-allocator-reduction-small-platforms=262144"</br>
"memorysetup-allocator-temp-initial-block-size-main=262144"</br>
"memorysetup-allocator-temp-initial-block-size-worker=262144"</br>
"memorysetup-temp-allocator-size-background-worker=32768"</br>
"memorysetup-temp-allocator-size-job-worker=262144"</br>
"memorysetup-temp-allocator-size-preload-manager=262144"</br>
"memorysetup-temp-allocator-size-nav-mesh-worker=65536"</br>
"memorysetup-temp-allocator-size-audio-worker=65536"</br>
"memorysetup-temp-allocator-size-cloud-worker=32768"</br>
"memorysetup-temp-allocator-size-gfx=262144"</br>
已放弃</br>
</details>

<details>
<summary> UnityPlayer.log</Summary>
The selected window backend is x11 </br>
Received signal SIGABRT (6) - code:-6 errno:0 addr:0x3e80000668d</br>
Obtained 17 stack frames.</br>
#0  0x007f544b0c59da in (Unknown)</br>
#1  0x007f544b0cf949 in (Unknown)</br>
#2  0x007f5449e41260 in (Unknown)</br>
#3  0x007f5449e9687b in pthread_kill</br>
#4  0x007f5449e411b6 in raise</br>
#5  0x007f5449e268ba in abort</br>
#6  0x007f5444f9efc4 in (Unknown)</br>
#7  0x007f5445003256 in (Unknown)</br>
#8  0x007f54450454fe in (Unknown)</br>
#9  0x007f5445035d65 in (Unknown)</br>
#10 0x007f5444da173a in il2cpp_init</br>
#11 0x007f544b02a43a in (Unknown)</br>
#12 0x007f544b0b3824 in (Unknown)</br>
#13 0x007f544b0b42bf in PlayerMain(int, char**)</br>
#14 0x007f5449e27f8e in (Unknown)</br>
#15 0x007f5449e28049 in __libc_start_main</br>
#16 0x00000000201029 in (Unknown)</br>
</details>
**Additional context | 补充信息**

**Comment by pirunxi** [comment]
按照bug反馈模板的要求，提供相关信息给我们的技术支持 https://hybridclr.doc.code-philosophy.com/docs/help/issue 。在新手群中发给他即可，我们会核实查一下。请在QQ上进行后续沟通。

**Comment by pirunxi** [comment]
感谢。我们已经确认，这个问题是6000.0.6版本引入的global-metadata格式改动引起。目前这个问题同样的在2021.3.39及2022.3.33版本有，但已经在6.2和6.3版本修复了。我们将在下个版本合并6000分支的最新il2cpp代码，解决这个问题。 目前临时解决办法为暂时使用6000.0.5或者更低版本
