### ISSUE TITLE
UnityEngine在打包后被裁剪部分如果想调用怎么办？

### ISSUE THREAD

**Issue by sqiuzhao** [focus-creative-games/hybridclr#140]
UnityEngine在打包后被裁剪部分如果想调用，是通过补充元数据的方式使用，还是无条件可以直接使用，或者说热更dll中不能使用这些被裁剪的代码，只能重新打包。

**Comment by pirunxi** [comment]
补充元数据解决的是泛型问题，跟你说的裁剪问题是两个独立的问题。 被裁剪后一般只能重新打包。如果被裁剪的类型是纯c#类型，不涉及到extern函数，则也可以将被裁剪的代码复制到热更新程序集中，改为引用这个热更新程序集中的该类型。不过除非极有必要，不太推荐这么做。 

如果还有疑问请详细阅读文档，或者去新手群交流。
