### ISSUE TITLE
用于补充元素据得三个dll  (mscorlib.dll,System.Core.dll.bytes，System.dll.bytes）是固定不变的吗？

### ISSUE THREAD

**Issue by sqiuzhao** [focus-creative-games/hybridclr#141]
请问一下，用于补充元素据得三个dll  (mscorlib.dll,System.Core.dll.bytes，System.dll.bytes）是固定不变的吗，也就是无论我用了多少泛型，也可能是UnityEngine中的泛型，也是只要补充这三个dll元数据吗？

**Comment by pirunxi** [comment]
补充什么，是根据你用到哪个aot dll中的泛型决定的。这三个dll比较常用，因而基本上都会用到其中的泛型，所以在示例项目中默认加入到了补充元数据列表。如果你没用到其中的泛型，是可以不补充的。具体请查阅文档 https://hybridclr.doc.code-philosophy.com/docs/basic/aotgeneric 或者去新手群交流。

**Comment by sqiuzhao** [comment]
谢谢老板
