### ISSUE TITLE
团结引擎这里会崩溃

### ISSUE THREAD

**Issue by leinlin** [focus-creative-games/hybridclr#143]
https://github.com/focus-creative-games/hybridclr/blob/b6b2b0d41f03fca18de7f998c9086d6e953ed832/hybridclr/metadata/Image.cpp#L868

**Comment by leinlin** [comment]
#if UNITY_ENGINE_TUANJIE
            result = il2cpp::vm::Class::GetOrSetupOneVTableSlot(klass, NULL, method->slot)->method;
#else
            result = klass->vtable[method->slot].method;
#endif

**Comment by pirunxi** [comment]
我们万万想不到，你使劲抹黑造谣hybridclr后居然还继续用hybridclr？居然有人可以厚脸皮到这种程度。

只发一个截图能解决什么问题呢？联系我们的付费技术支持。
