### ISSUE TITLE
关于桥接函数MethodBridge的崩溃

### ISSUE THREAD

**Issue by dragon3707** [focus-creative-games/hybridclr#145]
**Describe the bug | 描述问题**
线上运行的项目发生的崩溃

** Enviroment | 环境 **
- Unity Version: Unity 2021.3.30f1
-  com.code-philosophy.hybridclr Version: v4.0.15
- Platform: Android 14,level 34, arm64-v8a（Xiaomi Redmi Turbo 3 (5G)）

**Screenshots | 截图或者日志**
#00 pc 00000000013da1cc /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]
#01 pc 00000000013430b8 /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]

********** Crash dump: **********
hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/interpreter\Interpreter_Execute.cpp:1643:0
__N2M_vui4ui4(unsigned long, int, unsigned long, int, MethodInfo const*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/generated\MethodBridge.cpp:131004:5
hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/interpreter\Interpreter_Execute.cpp:5540:9
__N2M_vu(unsigned long, MethodInfo const*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/generated\MethodBridge.cpp:128094:5
hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/interpreter\Interpreter_Execute.cpp:4938:13
#05 0x00000000013430b8 /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]
__N2M_vui4ui4(unsigned long, int, unsigned long, int, MethodInfo const*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/generated\MethodBridge.cpp:131004:5
#06 0x00000000013dadec /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]
hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/interpreter\Interpreter_Execute.cpp:5540:9
#07 0x00000000013413c0 /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]
__N2M_vu(unsigned long, MethodInfo const*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/generated\MethodBridge.cpp:128094:5
#08 0x00000000013e4f4c /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]
hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*)
E:/soccer_client_3/online/origin/v5.6.0_Intranational/common/AndroidBuildNewSoccer/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/libil2cpp/hybridclr/interpreter\Interpreter_Execute.cpp:4938:13
#09 0x00000000013430b8 /data/app/~~rGiGk0qIKRuQ0-SQBZc0nw==/com.galasports.championsfc.mi-gg8NYknIrcwy0ddPK8W6mw==/lib/arm64/libil2cpp.so [arm64-v8a::8c704b66cba339e56eb543490d20a460]
__N2M_vui4ui4(unsigned long, int, unsigned long, int, MethodInfo const*)
![Dingtalk_20241011172340](https://github.com/user-attachments/assets/cabd866d-28da-4695-91e9-d2d21dbc5037)

**Additional context | 补充信息**
没有稳定复现步骤所以提供不了工程，抱歉。如果有收到过这样的问题反馈请指点下，感谢！

**Comment by pirunxi** [comment]
你的版本太旧，请更到最新版本。如果还有问题，需要付费技术支持，价格最低2000起。

建议新手群交流解决，因为免费。

**Comment by dragon3707** [comment]
感谢！
