### ISSUE TITLE
预制件加载后闪退

### ISSUE THREAD

**Issue by yingnierxiao** [focus-creative-games/hybridclr#146]
**Describe the bug | 描述问题**

** Enviroment | 环境 **

- Unity Version: 2022.3.41f1
-  com.code-philosophy.hybridclr Version: 6.10.0 or 6.6.0
- Platform: Android

**To Reproduce | 复制步骤 **

Please provide a reproduction project. Please try to reproduce this bug on the https://github.com/focus-creative-games/hybridclr_trial project. | 提供复现工程，请尽量在 https://github.com/focus-creative-games/hybridclr_trial 项目上复现这个bug。

Steps to reproduce the behavior :
暂时没有复现的工程

**Expected behavior | 期望的结果**

**Screenshots | 截图或者日志**
![image](https://github.com/user-attachments/assets/73d53854-f67c-4c64-830b-efb9c5f876fc)

**Additional context | 补充信息**
应该是加载完预制报错了，加载的预制使用的UniTask来实现，比较奇怪的debug模式下，没有问题，发布版本就出现闪退了，排查了代码应该是出现在预制加载后的时候，刚刚把UniTask修改为Task的实现，发现不会闪退了，暂时不知道是什么原因引起的

**Comment by pirunxi** [comment]
这个不是bug，去新手群交流吧。另外旧版本即使有bug我们也不会修复。你更新到最新版本吧。
