### ISSUE TITLE
AddComponent在挂载不在assembly列表文件内的dll脚本时单次调用时间会随着掉用次数的增加而增加

### ISSUE THREAD

**Issue by Moni-creator** [focus-creative-games/hybridclr#147]
Unity版本：2021.3.25
操作系统：Windows 11
BuildTarget：Android 64
com.code-philosophy.hybridclr的版本号：v6.10.1
截图及日志文件
![image](https://github.com/user-attachments/assets/517e8316-9839-4f5a-84ec-d96a5e930baf)

1. 加载一个不属于assembly列表文件的DLL
2. 多次调用AddComponent将DLL中的脚本挂载到物体上（连续执行1000比较明显）
3. 重复挂载会发现每次操作都会比上次多几百毫秒

**Comment by pirunxi** [comment]
明显无关

**Comment by Moni-creator** [comment]
![a328e9673dcd29ed47934473d2f2d6a0](https://github.com/user-attachments/assets/d2ff49d0-6dfd-4e5b-9a51-fc79c36418a2)
ComTest是一个什么代码都没有的脚本

**Comment by pirunxi** [comment]
这个问题确实跟我们没有关系，主要跟Unity引擎自身实现有关
