### ISSUE TITLE
是否无法进行Profiler真机调试的打包

### ISSUE THREAD

**Issue by DingfengTJJ** [focus-creative-games/hybridclr#15]
勾选了BuildSettings的
Development Build
AutoConnect Profiler
Deep Profiling Support
Script Debugging
打包报错
`Exception: Unity.IL2CPP.Building.BuilderFailedException: D:\Program Files\Unity\Hub\Editor\2020.3.33f1c2\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++ @"C:\Users\SHDTY\AppData\Local\Temp\tmp2691.tmp" -o "C:\Users\SHDTY\Desktop\Example\Client2020333\Library\il2cpp_android_armeabi-v7a\il2cpp_cache\linkresult_6B9F27354AC80744EDA767CE9AB4712F\libil2cpp.so" -shared -Wl,-soname,libil2cpp.so -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id -stdlib=libc++ -static-libstdc++ -target armv7-linux-androideabi19 -Wl,--wrap,sigaction "D:\Program Files\Unity\Hub\Editor\2020.3.33f1c2\Editor\Data\PlaybackEngines\AndroidPlayer\Variations\il2cpp\Development\StaticLibs\armeabi-v7a\baselib.a" -llog -rdynamic -fuse-ld=gold.exe

C:\Users\SHDTY\Desktop\Example\Client2020333\HybridCLRData\LocalIl2CppData\il2cpp\libil2cpp\vm-utils/Debugger.cpp:250: error: undefined reference to 'mono_debugger_agent_init_minimal'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

   at Unity.IL2CPP.Building.CppProgramBuilder.PostprocessObjectFiles(HashSet`1 objectFiles, CppToolChainContext toolChainContext)
   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   at il2cpp.Compilation.CompilationDriver.Run(RuntimePlatform platform, BuildingOptions buildingOptions, ReadOnlyCollection`1 matchedAssemblyMethodSourceFiles)
   at il2cpp.Program.DoRun(String[] args, RuntimePlatform platform, BuildingOptions buildingOptions, Boolean throwExceptions)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo) (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data) (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEditor.Android.PostProcessor.Tasks.RunIl2Cpp.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5c66c398f62f41bd9a3f1a9c5e45d135>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <5c66c398f62f41bd9a3f1a9c5e45d135>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <5c66c398f62f41bd9a3f1a9c5e45d135>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <5c66c398f62f41bd9a3f1a9c5e45d135>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <8d4895b259be41298a685a0c9b423575>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
`

**Comment by pirunxi** [comment]
可以的。 参见这个链接 https://forum.focus-creative-games.com/topics/41

**Comment by alpha-xdream** [comment]
> 

链接打不开

**Comment by NicoIer** [comment]
同问，在通过USB远程调试Andorid时，是否无法在热更程序集中打断点调试
