### ISSUE TITLE
关于新增热更新Assembly Definitions

### ISSUE THREAD

**Issue by cxh515** [focus-creative-games/hybridclr#150]
**Describe the bug | 描述问题**
假如本身有一份热更dll: GameLogic.dll已经打包热更线上,  后续某天想新增Session1.dll，Session2.dll等，这种情况是支持的吗？
目前我调试下来直接报错。难道是需要一开始规划预留好Session1.dll...这样？
或者是我测试的时候操作不当？

**Comment by pirunxi** [comment]
完全支持。想问什么去新手群交流
