### ISSUE TITLE
unity6 泛型缺少元数据或类型被裁剪,没有任何日志,直接函数断掉

### ISSUE THREAD

**Issue by mi1890** [focus-creative-games/hybridclr#151]
**Describe the bug | 描述问题**
unity6 泛型缺少元数据或类型被裁剪,没有任何日志,直接函数断掉
之前用unity2021版本,hybirdclr会输出日志提示缺少的类型或问题

** Enviroment | 环境 **

- Unity Version: 6000.0.23f1
-  com.code-philosophy.hybridclr Version: 7.2.0
- Platform:  Android

**To Reproduce | 复制步骤 **
去掉补充元数据
进入游戏,可以看到没有任何日志提示

**Expected behavior | 期望的结果**
能正确输出日志

**Comment by pirunxi** [comment]
就这？
