### ISSUE TITLE
Crash：热更类实现AOT泛型接口（UniTask）会闪退

### ISSUE THREAD

**Issue by LiuMir** [focus-creative-games/hybridclr#152]
**Describe the bug | 描述问题**

我在热更代码中实现AOT泛型接口 UniTask<Info（自定义结构体，也在AOT里）> GameMainTest() 程序会在return时闪退。由于使用了UniTask，我并不清楚是UniTask还是HybridCLR导致。麻烦大佬抽空帮忙看看，十分感谢。
PS:我写了一个比较demo并且以附件形式放在末尾。主要代码在Launcher.cs(AOT)、IGameMain.cs(AOT)、GameMain.cs(Hotupdate)

** Enviroment | 环境 **

- Unity Version: 6000.0.17f1
-  com.code-philosophy.hybridclr Version: 6.9.0 | 7.2.0
- Platform: Win 64 Standalone

**To Reproduce | 复制步骤 **

Please provide a reproduction project. Please try to reproduce this bug on the https://github.com/focus-creative-games/hybridclr_trial project. | 提供复现工程，请尽量在 https://github.com/focus-creative-games/hybridclr_trial 项目上复现这个bug。

Steps to reproduce the behavior :
1. AOT构建自定义Struct（Info）, 构建自定义Interface（UniTask<Info> GameMainTest()） 
2. Hotupdate构建自定义类并且实现自定义Interface
3. Launcher调用Hotupdate里实现自定义Interface的函数
4. Crash

**Expected behavior | 期望的结果**
程序不会Crash

**Screenshots | 截图或者日志**
![AOT](https://github.com/user-attachments/assets/32d8fc33-c5d5-4f3b-8875-60abe51ea269)
![Hotupdate](https://github.com/user-attachments/assets/4477e842-4959-485a-b07a-597d756762d5)
![Crash](https://github.com/user-attachments/assets/45977843-6d89-47a0-8c5c-699cb238a9cb)

**Additional context | 补充信息**
[externalPackage.zip](https://github.com/user-attachments/files/18206720/externalPackage.zip)

**Comment by pirunxi** [comment]
常见错误有这个。还有问题去新手群问。

**Comment by LiuMir** [comment]
感谢回复。
![image](https://github.com/user-attachments/assets/f69840bb-03f5-4861-ae0c-5b5594d8b76f)
如果说的是按这个处理的话，我已经按这个试过仍然crash。我写的测试demo里 unitask<struct>会闪退， unitask<class>运行正常。
![image](https://github.com/user-attachments/assets/c94a7800-0347-4a36-ac7a-424f0b957b97)

再次感谢回复，我去新手群里咨询。

**Comment by LiuMir** [comment]
![image](https://github.com/user-attachments/assets/c389dc2f-e8c7-4c91-b5a2-beab5e5cb52c)
群友回复
