### ISSUE TITLE
calli 的实现问题

### ISSUE THREAD

**Issue by AlanLiu90** [focus-creative-games/hybridclr#17]
看 calli 实现的时候，发现 Image::ReadStandAloneSig 中，params 没有赋值给 methodSig.params。我自己本地尝试修复时，还发现了其他问题，感觉 cali 的实现可能没有测过，hybridclr_test 也没看到相关的测试用例。

这里写下我的测试方法，希望能提供帮助。

1. 在nuget下载runtime.win-x64.microsoft.netcore.ilasm.6.0.0.nupkg，解压可以拿到 ilasm.exe
2. 为下面的IL代码（保存到 il.txt 文件中），生成 Assembly：`ilasm /DLL il.txt /OUTPUT=MyTest.dll`
3. 把 MyTest.dll 放到Unity工程中，当作 Hotfix dll
4. 以 hybridclr_trial 为例，在 Assembly-CSharp 中，调用 `A.TestCalli()`
5. 修改代码，让打包版本可以加载到 MyTest.dll
6. 运行Win64版本，会看到程序触发了断言

```
.assembly extern mscorlib
{
    auto
}
.assembly MyTest {}
.module MyTest.dll
.class public A
{
    .method public specialname void .ctor()
    {
        ldarg.0
        call instance void [mscorlib]System.Object::.ctor()
        ret
    }
    
    .method public static void Test2(int32 param_0)
    {
        ldarg.0
		box [mscorlib]System.Int32
        call void [UnityEngine.CoreModule]UnityEngine.Debug::Log(object)
        ret
    }
	
	.method public static void TestCalli()
	{
		.locals (class A a,int32 v_1)

		ldftn void A::Test2(int32)
		stloc.1
		ldc.i4 123
		ldloc.1
		calli void(int32)

		ret
	}  
}
```

**Comment by pirunxi** [comment]
确实是少数几个没有实现的指令，因为得如你这样构造用例。我们晚些时候修正处理。

**Comment by pirunxi** [comment]
已经修复提交。如有问题，及时跟我们反馈。
