### ISSUE TITLE
ENABLE_PLACEHOLDER_DLL关闭可能会编译报错

### ISSUE THREAD

**Issue by zvars** [focus-creative-games/hybridclr#18]
Assembly.cpp中
`Il2CppAssembly* Assembly::Create(const byte* assemblyData, uint64_t length, bool copyData)`中调用的`FindPlaceHolderAssembly`声明&实现都是被包在`#if ENABLE_PLACEHOLDER_DLL == 1`中。
如果删除了Il2CppCompatibleDef.h中删除了`#define ENABLE_PLACEHOLDER_DLL 1`，
这样编译时会引起找不到函数的错误

**Comment by pirunxi** [comment]
已修复。感谢。
