### ISSUE TITLE
Export Project到Android Studio打出来的包不能正常运行!!!

### ISSUE THREAD

**Issue by mohusheng** [focus-creative-games/hybridclr#20]
手机连接到Logcat会发现第二次IL2CPP的JNI_OnLoad日志没有打印出来。
没有异常报错。
画面显示一个天空盒就不继续往下执行。

hybridclr最新版，2021.3.6f1和2021.3.11f1测试都有这个问题。

**Comment by pirunxi** [comment]
你场景脚本missing引起，请看文档的monobehaviour工作流介绍。交流请去去新手群问。
