### ISSUE TITLE
想问问加载assetbundle里的代码后，在卸载assetbundle后能不能卸载掉代码再加载别的assetbundle的代码啊？

### ISSUE THREAD

**Issue by huangjun198604** [focus-creative-games/hybridclr#27]
想问问加载assetbundle里的代码后，在卸载assetbundle后能不能卸载掉代码再加载别的assetbundle的代码啊？

**Comment by Bian-Sh** [comment]
从底层实现上来看，暂时不支持

**Comment by Bian-Sh** [comment]
但是 hybridclr 尝试有限支持，你可以持续关注

**Comment by pirunxi** [comment]
这个功能不是规范中的功能，所以可能会提供一个简略的预览分支，但加入到主干分支中。想要更深入的支持请找我们的商业化支持。

**Comment by huangjun198604** [comment]
我们现在用xlua，好像能卸载虚拟机。hybirdclr我想的方案如果不能unload掉dll就是用新的dll加载覆盖旧的也行

**Comment by pirunxi** [comment]
il2cpp上实现这种功能也是可行的。上限更高。由于它是非规范的内容，无法加入正式功能。有需要可以寻求商业化支持。
