### ISSUE TITLE
Android上运行Await报错

### ISSUE THREAD

**Issue by Difficulty-in-naming** [focus-creative-games/hybridclr#28]
Unity Editor:2021.3.9
系统:Android10 - 12
BuildTarget : ARM64
hybridclr : 0.6.1
il2cpp_plus仓库版本:![image](https://user-images.githubusercontent.com/8246779/203285487-edabf978-7213-49d3-a28f-5a983c3e7a51.png)
截图:
![N2X8565` RN_`U24U1MA7)C](https://user-images.githubusercontent.com/8246779/203283946-57b1f57a-88e7-4334-8a99-56868e20f370.png)
![Z~$~P}RMNKVHR1HA3{D7NCB](https://user-images.githubusercontent.com/8246779/203284098-74bde3cb-e45d-4d93-a384-0462bbefda67.png)

在多份线上报错日志中报错堆栈都是Hotfix代码await调用AOT代码发生的报错.

**Comment by pirunxi** [comment]
只有这个信息，如果没有可复现的工程，很难解决。而且你这们版本也是旧的。可能包含一些已经修复的bug。

**Comment by Difficulty-in-naming** [comment]
> 只有这个信息，如果没有可复现的工程，很难解决。而且你这们版本也是旧的。可能包含一些已经修复的bug。

你好.感谢回复.,最近看到HybridCLR有SuperSet功能还挺心动的.但是项目已经在线上跑了.如果我们现在从0.6.1版本升级到最新版本会稳定一些吗

**Comment by Difficulty-in-naming** [comment]
最终我们似乎从更深的日志中发现了问题.
似乎是Firebase Auth发生了错误.
所以不是HybridCLR的问题
关闭这个Issues

**Comment by pirunxi** [comment]
0.10.x 版本修复了一些新的bug，所以升级到最新是更稳定一点的。
