### ISSUE TITLE
netstandard 2.1

### ISSUE THREAD

**Issue by Sarofc** [focus-creative-games/hybridclr#3]
大佬，请问有计划支持 netstandard 2.1 嘛

**Comment by Sarofc** [comment]
看了下，unity2021.2以上的版本.net framework选项包含了netstandard 2.1的api。。。

**Comment by happygameboy-lu** [comment]
我不是官方人员，你问一下官方吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "focus-creative-games/hybridclr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 下午5:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[focus-creative-games/hybridclr] netstandard 2.1 (Issue #3)





 
大佬，请问有计划支持 netstandard 2.1 嘛
