### ISSUE TITLE
调用key为枚举类型的Dictionary的TryGetValue，有内存分配的问题

### ISSUE THREAD

**Issue by AlanLiu90** [focus-creative-games/hybridclr#33]
## 测试环境
* Unity 2020.3.30
* Windows 10
* Win64 的包

## 问题
调用key为枚举类型的Dictionary的`TryGetValue`，有内存分配。查了下，内存分配是在其中调用的`FindEntry`里：
```cs
private int FindEntry(TKey key) {
	if( key == null) {
		ThrowHelper.ThrowArgumentNullException(ExceptionArgument.key);
	}

	// ...
}
```

这个代码被编译成了下面的IL：
```
IL_0000: ldarg.1
IL_0001: box !TKey
IL_0006: brtrue.s IL_0013

IL_0008: ldstr "key"
IL_000d: newobj instance void System.ArgumentNullException::.ctor(string)
IL_0012: throw
```

其中的box指令导致了内存分配。

IL2CPP没这个问题，因为它把整个分支都优化掉了。

**Comment by pirunxi** [comment]
感谢反馈。由于目前指令集transform时是一对一转换，未作任何优化，故这条指令如果不看上下文，是不可能直接优化掉的。我们将会在后面的指令优化版本彻底解决这个问题。

一个临时方案是你可以手动插入代码，对 box, brxxx 这种模式的代码执行一个非装箱的无条件跳转操作。

**Comment by AlanLiu90** [comment]
了解。我自己本地已经先这样改过，测试起来是没问题。
