### ISSUE TITLE
RequireComponent不被调用

### ISSUE THREAD

**Issue by NeverMore-Father** [focus-creative-games/hybridclr#34]
- Unity Editor版本。2020.3.33f1c2
- 操作系统。 Win 10
- 出错的Build Target。win64。
- com.focus-creative-games.hybridclr_unity的版本号 Version 1.1.15
- 仓库版本号 
![image](https://user-images.githubusercontent.com/36830623/209630867-19411552-ea03-4fae-aaf6-38903bcc5e8e.png)

问题描述：
脚本Gan添加[RequireComponent(typeof(Player))]属性，在HotUpdateMain中 gameObject.AddComponent<Gan>();发现Player并未加载。

**Comment by Rigyuki** [comment]
这个是unity自己的bug
