### ISSUE TITLE
hotfix dll 中使用UniTask 在WebGL上运行内存出错

### ISSUE THREAD

**Issue by WestallZhu** [focus-creative-games/hybridclr#37]
1，hybridclr_trial-main 中导入UniTask  https://github.com/Cysharp/UniTask
2，HotUpdate目录添加hotfix 测试代码
public class HotUpdateMain1
{
    public static async UniTaskVoid UTaskHotFIxTest()
    {
        Debug.Log("UTaskHotFIxTest OK");
        await UniTask.CompletedTask;
    }

    public static void  Start()
    {
        UTaskHotFIxTest().Forget();
    }
}
3，修改LoadDll.cs
3.1添加 AOT dll
  public static List<string> AOTMetaAssemblyNames { get; } = new List<string>()
  {
      "mscorlib.dll",
      "System.dll",
      "System.Core.dll",
      "UniTask.dll",
  };
3.2 修改StartGame 添加HotUpdateMain1测试调用
    void StartGame()
    {
        LoadMetadataForAOTAssemblies();

        System.Reflection.Assembly hotFixDll = null;
#if !UNITY_EDITOR
        hotFixDll = System.Reflection.Assembly.Load(GetAssetData("Assembly-CSharp.dll"));
#else
        hotFixDll = AppDomain.CurrentDomain.GetAssemblies().First(assembly => assembly.GetName().Name == "Assembly-CSharp");
#endif

        AssetBundle prefabAb = AssetBundle.LoadFromMemory(GetAssetData("prefabs"));
        GameObject testPrefab = Instantiate(prefabAb.LoadAsset<GameObject>("HotUpdatePrefab.prefab"));

        System.Reflection.MethodInfo methodInfo = hotFixDll.GetType("HotUpdateMain1").GetMethod("Start");
        object[] param = new object[methodInfo.GetParameters().Length];
        methodInfo.Invoke(null, param);
    }
4,webgl报错信息
"An error occurred running the Unity content on this page. See your browser javaScript console for more info. the error was:
RuntimeError:null function or function signature mismatch at .."

pc android 正常运行，unity 版本 2021.3.13   hybridclr 1.0  il2cpp_plus 2021.3.1

**Comment by pirunxi** [comment]
按照bug反馈要求，给得清楚一点。我们不熟悉ET。

**Comment by pirunxi** [comment]
由于成本原因，WebGL版本保持现状，不会再维护了。只会对商业化客户提供有限的支持。

**Comment by EP-Toushirou** [comment]
同样用UniTaskVoid在WebGL报错, 全部改成普通的async void函数就好了

**Comment by xyq10612** [comment]
感谢，就是UniTaskVoid的问题，改成async void解决了

**Comment by pirunxi** [comment]
UniTask我们都已经测试过的，这部分使用的人很多，不太可能有错。 如果有错，那也是我们的bug，跟UniTaskVoid无关。请按照 https://hybridclr.doc.code-philosophy.com/docs/help/issue 提供复现工程给我们
