### ISSUE TITLE
Assembly.Load加载hotfix.dll时报错

### ISSUE THREAD

**Issue by daibao520** [focus-creative-games/hybridclr#38]
unity editor版本：2021.3.10f1c1
操作系统：Windows 11 专业版
Build Target：Windows 64bit
com.focus-creative-games.hybridclr_unity的版本号：1.1.4
git main分支更新到：支持自定义外部热更新dll的搜索路径 externalHotUpdateAssembliyDirs walon <walon@focus-creative-games.com> abc70a7ffc52c795dc3f8fe32c7151d05c2c49c2 2022/12/2 10:33:13
复现条件：只要把我上传的代码加进hotfix.dll里，运行到Assembly.Load加载hotfix.dll就会报错
[Kcp.zip](https://github.com/focus-creative-games/hybridclr/files/10424510/Kcp.zip)

**Comment by daibao520** [comment]
![image](https://user-images.githubusercontent.com/6234955/212648527-c869f493-f2bd-4205-ae83-22a5a5c2df62.png)

**Comment by pirunxi** [comment]
该问题在hybridclr_trail项目上用最新的hybridclr_unity及最新的hybridclr+il2cpp_plus代码无法复现。我们不会再去测试旧版本的代码，所以请更到最新后再测试一次，如果复测成功，将工程发给我们。
