### ISSUE TITLE
CompareTypeLayout没有正确处理值类型

### ISSUE THREAD

**Issue by AlanLiu90** [focus-creative-games/hybridclr#41]
## 环境
Unity: 2020.3.42
il2cpp_plus: 2020-DHE
hybridclr: DHE
hybridclr_unity: DHE
OS+Build: Windows 10 64 bit

## 问题
对于值类型，`td1.IsClass`和`td1.IsValueClass`同时为true，但是`IsClass`的分支在前面，导致处理值类型的分支不会执行到

在dhe_demo中使用下面的代码可以复现问题：
```cs
public class Case8
{
#if DHE_HOT_UPDATE
    [StructLayout(LayoutKind.Auto, Size = 32)]
#endif
    public struct Color
    {
        public float R, G, B, A;
    }

    public unsafe static void Run()
    {
        Debug.Log(sizeof(Color));
    }
}

void Start()
{

	// Run("函数未变化，运行AOT版本", RunNotChangedMethod);
	// Run("函数有变化，运行解释器版本", RunChangedMethod);

	Case8.Run();
}
```

期望输出：32
实际输出：16

**Comment by pirunxi** [comment]
非常感谢。已经修复此bug。更新最新hybridclr_unitiy DHE分支即可。现在对外发布的版本不包含间接函数调用的优化，是否可以邀请你作为免费的商业用户，我们提供最新的代码，帮助我们更快地清除问题？ 我们的技术支持QQ 1732047670。

**Comment by AlanLiu90** [comment]
感谢邀请，我在QQ加这个号时，提示“只加付费后的商业化用户”，需要验证，我要怎么联系你们呢？

**Comment by pirunxi** [comment]
你再试一次。

**Comment by pirunxi** [comment]
没收到加好友通知。 确认这个号： 1732047670 技术支持

**Comment by AlanLiu90** [comment]
我昨天晚上、今天上午，又发了加好友申请，但目前没收到通过的通知，不知道是不是你那边没收到？我刚才和同事测了下，是可以加他的好友的。

要不我们用邮件联系？（刚才尝试给1732047670@qq.com发邮件，提示 Address not found）

**Comment by pirunxi** [comment]
ok，发邮件 walon@focus-creative-games.com，告诉我你的QQ号，我来加你。
