### ISSUE TITLE
模拟器下未正确生成桥接函数：NotSupportNative2Managed

### ISSUE THREAD

**Issue by 17844560** [focus-creative-games/hybridclr#42]
我的hybridclr unity package是  2.0.1 unity版本2021.3.16f1c1
原来项目是unity2020.3.33f1c1 没有任何问题,  升级unity2021后，真机一切正常，模拟器出现NotSupportNative2Managed，出问题的函数如下
![3B01BEB5-7E75-46DD-AA12-E1D18F432B46](https://user-images.githubusercontent.com/48268817/217709722-d5828713-21da-4a6f-a482-7a838bdd550c.png)
![image](https://user-images.githubusercontent.com/48268817/217709752-1d83dd33-1a64-4ce2-a0fe-0b85458e83a3.png)

**Comment by pirunxi** [comment]
按照要求在hybridclr_trial基础上给一个最小可复现的工程，方便我们复现和定位问题。感谢！可以直接发给商业技术支持  1732047670

**Comment by 17844560** [comment]
@pirunxi 复现的工程已经发给技术，和我原项目有点不一样，原项目在真机上没有问题，示例项目复现后在真机模拟器都有问题，真机hybridclr_unity 版本是2.0.3我原项目是2.0.1 使用了一个第三方的Dll System.Reactive.dll

**Comment by 17844560** [comment]
@pirunxi 哥 你有空闲的时间，看下这个呢，哪个桥接函数没扫描到，或者有隐藏代码生成，我看了System.Reactive.dll的源码，实在没找到哪里有问题

**Comment by pirunxi** [comment]
我们的研发已经解决这个问题。不过请先邮箱跟商务同事联系，走商业化途径。
