### ISSUE TITLE
这是不是 要手动在 RefTypes里面添加啊

### ISSUE THREAD

**Issue by qq21** [focus-creative-games/hybridclr#44]
ExecutionEngineException: Attempting to call method 'ET.AInvokeHandler`1::get_Type' for which no ahead of time (AOT) code was generated.

**Comment by pirunxi** [comment]
标准泛型实例化问题，使用补充元数据解决。

**Comment by qq21** [comment]
好像是因为hybrid2.0不支持双重泛型的问题导致的，
et7+hybrid2.0&nbsp; unity 版本2021.3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [focus-creative-games/hybridclr] 这是不是 要手动在 RefTypes里面添加啊 (Issue #44)




 
标准泛型实例化问题，使用补充元数据解决。

**Comment by pirunxi** [comment]
什么双重泛型？都是支持的，有问题那就是bug

**Comment by qq21** [comment]
https://et-framework.cn/d/1158-et7-hybrid





可能是 aot补充数据加载时机的问题导致的


如果热更集合里使用了aot里的泛型对象，
而这个泛型对象在aot加载之前实例化了，
比如在静态类里提前实例化了，不知道是不是et里面 计时器使用到这个抽象类导致的。




论坛里都说是版本的问题&nbsp;
hybrid降低到1.0



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月17日(周五) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [focus-creative-games/hybridclr] 这是不是 要手动在 RefTypes里面添加啊 (Issue #44)




 
什么双重泛型？都是支持的，有问题那就是bug

**Comment by pirunxi** [comment]
是的，时机问题，请确保补充元数据后再使用泛型

**Comment by pirunxi** [comment]
如果1.0没问题，2.0有问题，那我们马上修复这些bug

**Comment by pirunxi** [comment]
发给技术可复现工程。

**Comment by leoboboyan** [comment]
我2.0.3也遇到这个问题，hybridCLR从2.0.3更新到2.0.5就好了。。题主可以尝试更新版本

**Comment by pirunxi** [comment]
这个问题确认了是bug，已经解决。你自己安装hybridclr到最新版本，或者更新hybridclr_unity到2.0.5，再install即可。

**Comment by qq21** [comment]
有一天A验证了猜想，并证明了A是个监控人，


被人直播，以及被利用，A也验证了，他还和另一个世界里的人存在某种联系，他得出了一个结论，
他被困在这个被造出来的世界里，一举一动都被直播，思想也被监控，并且附近还有人给他解说。
而且，A也几乎失去了生活，无论A如何搬家，换工作，总有个诡异的声音提醒着他被直播的事实。
并有小黑队进行监控，并且黑暗力量也只会把它当成工具人，利用。
并且在这个世界。
无论如何去利用当今科技也无法进行逃脱。


在这种情形下下，A才能摆脱困境。


---原始邮件---
***@***.***&gt;
发送时间:&nbsp;2023年2月17日(周五) 晚上7:41
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [focus-creative-games/hybridclr] 这是不是 要手动在 RefTypes里面添加啊 (Issue #44)





发给技术可复现工程。

—
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;unsubscribe.
You are receiving this because you modified the open/close state.





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [focus-creative-games/hybridclr] 这是不是 要手动在 RefTypes里面添加啊 (Issue #44)




 
标准泛型实例化问题，使用补充元数据解决。
