### ISSUE TITLE
DHE等价性计算的性能

### ISSUE THREAD

**Issue by AlanLiu90** [focus-creative-games/hybridclr#47]
在项目中测试了最新的hybridclr_unity，可以正常生成`Assembly-CSharp.dhao.bytes`了，但是执行一次耗时约7分钟（机器配置是 Windows 10 64 bit + i7-12700），感觉有点久。
我加了一些性能统计，生成了一个可以用`chrome://tracing/`查看的文件，请看下是否可以做一些优化，比如
* 缓存`CompareFieldOrParamOrVariableType`的结果
* 缓存`TryGetDHEMethodDef`的结果

[HybridCLRTEP.zip](https://github.com/focus-creative-games/hybridclr/files/10803836/HybridCLRTEP.zip)

**Comment by pirunxi** [comment]
之前主要考虑正确性，暂时没有进行优化。我们马上进行优化及加入多线程计算，应该可以大幅缩短计算时间
