### ISSUE TITLE
DHE计算等价性问题

### ISSUE THREAD

**Issue by AlanLiu90** [focus-creative-games/hybridclr#52]
## 环境

|                 |                   |
| --------------- | ----------------- |
| Unity           | 2020.3.33         |
| il2cpp_plus     | 2020-DHE          |
| hybridclr       | DHE |
| hybridclr_unity | DHE |
| OS+Build        | Windows 10 64 bit |
| project         | dhe_demo（没开间接函数优化）         |

## 问题
下面代码可复现问题（`B.Func1`被标记为变化，但`Case23.Run`和`HotUpdateMain .Start`没有被标记为变化）：
```cs
public interface IA
{
    void Func1();
}

public class B : IA
{
    public void Func1()
    {
#if DHE_HOT_UPDATE
        UnityEngine.Debug.Log("1");
#else
        UnityEngine.Debug.Log("2");
#endif
    }
}

public class Case23
{
    public static void Run()
    {
        var b = new B();
        b.Func1();
    }
}

public class HotUpdateMain : MonoBehaviour
{
    void Start()
    {
        Case23.Run();
    }
}
```

期望输出：1
实际输出：2

复现工程：[dhe_demo.zip](https://github.com/focus-creative-games/hybridclr/files/10893562/dhe_demo.zip)（如果单独使用上面代码复现不了问题，可以使用该工程）

**Comment by pirunxi** [comment]
修复了。更新 hybridclr_unity即可。
