### ISSUE TITLE
关于unity2021.3.14f版本之前的il2cpp构建失败bug

### ISSUE THREAD

**Issue by MuYanKang** [focus-creative-games/hybridclr#54]
相关报错是

`Building Library\Bee\artifacts\WebGL\il2cpp\master_WebGL_wasm\v0f6_eric2.lump.o failed with output:
In file included from Library/Bee/artifacts/WebGL/il2cpp/master_WebGL_wasm/33i3_Generic2.lump.cpp:7:
D:\Software\Unity\Unity2021.3.10f1\Unity 2021.3.10f1\Editor\Data\il2cpp\libil2cpp\os\Generic\Process.cpp:11:22: error: out-of-line definition of 'Times' does not match any declaration in 'il2cpp::os::Process'
    int64_t Process::Times(ProcessHandle* handle, int32_t type)
                     ^~~~~
D:\Software\Unity\Unity2021.3.10f1\Unity 2021.3.10f1\Editor\Data\il2cpp\libil2cpp\os\Generic\Process.cpp:17:22: error: out-of-line definition of 'StartTime' does not match any declaration in 'il2cpp::os::Process'
    int64_t Process::StartTime(ProcessHandle* handle)
                     ^~~~~~~~~
D:\Software\Unity\Unity2021.3.10f1\Unity 2021.3.10f1\Editor\Data\il2cpp\libil2cpp\os\Generic\Process.cpp:23:22: error: out-of-line definition of 'GetProcessData' does not match any declaration in 'il2cpp::os::Process'
    int64_t Process::GetProcessData(int32_t pid, int32_t data_type, int32_t* error)`

发现在更新3.14f版本是Process.h中这些函数被移除了
`static int64_t Times(ProcessHandle* handle, int32_t type);
static int64_t StartTime(ProcessHandle* handle);
static int64_t GetProcessData(int32_t pid, int32_t data_type, int32_t* error);`

因为我们目前在用unity2021.3.10f1进行开发，所以感觉这里在install时 再区分下unity2021.3.14f以下版本和以上的版本是不是比较好

**Comment by pirunxi** [comment]
2021.3.1和2021.3.16版本我们都测过是ok的，偏偏2021.3.14有问题？ 另外是全平台有问题还是只 webgl？

**Comment by MuYanKang** [comment]
不是2021.3.14,我用的是2021.3.10f1，2021.3.14是我查看process.h的历史记录看到修改日志是更新到3.14f

追加测试  切换到Android端，重新install， 2021.3.10f1 将il2Cpp复制到编辑器后
1-->不启用HybridCLR ，打包 ，失败
2-->启用HybridCLR，启用全局il2cpp，打包，失败
3-->启用HybridCLR，不启用全局il2cpp，打包，成功

WebGL端必须启用全局il2cpp，打包失败

**Comment by pirunxi** [comment]
3 启用hybridclr，不启用全局，为何能成功？

**Comment by MuYanKang** [comment]
目前我从报错信息和比较的文件结果看，在全局打包的时候Unity 2021.3.10f1\Editor\Data\il2cpp\libil2cpp\os\Generic下会生成process.cpp，但本地打包Generic里并不会生成process.cpp，其余我对il2cpp编译并不了解就不清楚了

**Comment by pirunxi** [comment]
当前最新版本并没有 os\Generic\Process.cpp 这个文件。如果全局打包时有这个文件，说明你没有正确替换安装目录下的libil2cpp，或者说Library目录下有打包缓存文件，导致出现这个错误。

**Comment by pirunxi** [comment]
当前最新版本并没有 os\Generic\Process.cpp 这个文件。如果全局打包时有这个文件，说明你没有正确替换安装目录下的libil2cpp，或者说Library目录下有打包缓存文件，导致出现这个错误。
