### ISSUE TITLE
unity2021.3.20f1c1下打包时错误，求解决方案

### ISSUE THREAD

**Issue by heimasi** [focus-creative-games/hybridclr#55]
抱歉，其实是在ET7版本里打包时发现的错误，但是猫大也没有遇到过这种情况，来这个咨询下大佬，打搅了！

ET版本: 7.2

Unity版本: 2021.3.20f1c1 apple silicon

Net版本: 6.0.407

在macos m1环境下，按照文档 打包过程，进行到第6步，第二次打包时，不选择build exe时，不报错，啥也打不出来。选择build exe时，报如图错误！大佬有碰到过吗？如何解决的，谢谢。

![image](https://et-framework.cn/assets/files/2023-03-26/1679832757-529719-2023-03-26-201144.png)

![image](https://et-framework.cn/assets/files/2023-03-26/1679832757-676882-2023-03-26-201128.png)

**Comment by pirunxi** [comment]
更新到最新hybridclr_unity，重新install即可解决
