### ISSUE TITLE
新老包同时在线上使用的兼容问题

### ISSUE THREAD

**Issue by NewbieGameCoder** [focus-creative-games/hybridclr#56]
![0FLT9SX8V2QQMNSV$N}QWLR](https://user-images.githubusercontent.com/17585924/228095730-3663b31f-3b67-46af-aaa5-e2ce33a17cf5.png)
由于默认会首先返回AOT dll。假如有A.dll在线上的所有较老包是AOT dll，在线上的所有较新包是Hot dll，那么Hot dll变动比较大的时候，解释执行其实是会有问题的。解释执行的问题诱因如下
![ZM)WB J(JXZU(%9$DQDTTAL](https://user-images.githubusercontent.com/17585924/228096265-5c926342-ca2a-40da-8fce-a2cc04f0b7e8.png)
![E@TPQ6KLR{D@XUP)X `W017](https://user-images.githubusercontent.com/17585924/228096279-62756aab-8b29-43a5-a4d0-f6d83cfcb12b.png)
![$(BCXGY@~TBJM YWGZE_D9I](https://user-images.githubusercontent.com/17585924/228096290-dd36f67a-d251-43a7-8cfd-e938524cd7dd.png)
这里其实是是会获取到的老的AOT相关的数据，因为是通过assembly name去获取相关的信息的，产生不可预知的错误。
且此时的其他部分的反射接口Assembly.Load("A.dll").GetType().GetMethod()这种，在所有较老包上也是会调用到老的AOT dll的相关方法，无法调用到新的Hot dll的相关方法。

**Comment by pirunxi** [comment]
新旧dll同名？ 这个问题我们很久前已知。

**Comment by NewbieGameCoder** [comment]
嗯嗯 跟新旧同名很像，逻辑意义上是同一个dll，但是这个dll中途转成了Hot dll，框架是支持本地有同名AOT dll的同时还能Assembly.Load同名Hot dll的。

**Comment by pirunxi** [comment]
没正确处理同名的原因是考虑到unity monobehaviour机制并不能正确处理多个同名dll的情况，索性将错就错，让错误暴露出来。如果不考虑monobehaviour，反向搜索dll可以解决你这个问题。

**Comment by NewbieGameCoder** [comment]
嗯嗯，我说的这种情况，一般只有兼容用的老包才有，且老包下载了同名的hot dll后还有不可预知的执行错误，如果能把错误明显的抛出来，也能加快定位问题所在。

**Comment by pirunxi** [comment]
逆序找就可以了，因为后面新增的ass必然在后面。另外 AOT的 AOTHomologousImage不会出现在那个列表，所以没有问题。 我们会晚些时候解决这个问题。

**Comment by NewbieGameCoder** [comment]
哦哦 对哦，AOTHomologousImage是走的LoadMetadataForAOTAssembly，有劳啦

**Comment by pirunxi** [comment]
但有另外一个问题，由于unity在启动时已经扫描了 aot dll中的monobehaviour，这个绑定是一次性的，不能更改，会导致你后面挂载在资源上的脚本创建出来的全是aot dll中monobehaviour（通过代码添加的可能没有这个问题），这是个非常严重的bug。除非你的aot dll中没有这样的类型。 建议仔细检查一下实践中是否能如期望运行。

**Comment by NewbieGameCoder** [comment]
收到，感谢提醒
