### ISSUE TITLE
请问，Generate All、补充元数据的DLL更新的执行时机的最佳实践？

### ISSUE THREAD

**Issue by ProgramForFun** [focus-creative-games/hybridclr#57]
请问，Generate All、更新补充元数据的DLL到我们自己的资源管理系统内，这两项操作的执行时机有最佳实践吗？

我看文档里提到了只有热更程序集代码变动的时候，只Compile热更程序集就好，那是不是意味着：

有AOT代码修改时，就需要执行Generate All、更新补充元数据的DLL到我们自己的资源管理系统内，这两项操作

**Comment by pirunxi** [comment]
1. 只在发布新的主包的时候才需要执行"Generate All、更新补充元数据的DLL" 这种操作。
2.  Genereal All操作中，经常发生变化的是桥接函数，但由于桥接函数生成非常完整，大多数桥接函数在热更新代码中并没有调用到。所以平时开发期，只要没有新增dll，不用重新generate all也影响不大，万一遇到错误再重新generate all就好。
3. 补充元数据只用到了泛型的元数据，如果你没有修改aot中的泛型类或者泛型函数的代码，并且使用了SuperSet模式，不更新补充元数据也无所谓。

总之，你得理解原理才能选择适合你的操作。

**Comment by ProgramForFun** [comment]
感谢回复
