### ISSUE TITLE
server build 打包失败

### ISSUE THREAD

**Issue by longde123** [focus-creative-games/hybridclr#58]
WindowsPlayer(2,PS2022EKOCCNKY) A scripted object (probably ProjectorForLWRP.ProjectorRendererFeature?) has a different serialization layout when loading. (Read 64 bytes but expected 76 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?

**Comment by longde123** [comment]
并没有 #ifdef UNITY_EDITOR

**Comment by pirunxi** [comment]
你在随包资源上挂载了热更新脚本。必须用ab
。
