### ISSUE TITLE
预留 ReversePInvokeWrapper 函数的最佳实践？

### ISSUE THREAD

**Issue by ProgramForFun** [focus-creative-games/hybridclr#59]
看了文档里**预留 ReversePInvokeWrapper 函数**那一节，示例是给带有MonoPInvokeCallbackAttribute特性的函数再增加[ReversePInvokeWrapperGeneration(int preserveCount)]来指定预留数量；

我想问下这块在具体操作上一般都是怎么做的，直接修改Lua框架的wrap生成代码吗？

**Comment by ProgramForFun** [comment]
如果是的话，这个预留数量一般写多少合适？

**Comment by pirunxi** [comment]
不用改xlua的代码，因为对于带MonoPInvokeCallbackAttribute的函数，自动会增加wrapper数量。 你要做的是预留足够多，也就是你写一个类似这样的代码，把下面的10改成你的预留数量即可（如1000）。但也别填过大的如几百万这样的数字，因为每个wrapper都会生成一个wrapper函数，如果过多，代码会急剧增加。

[ReversePInvokeWrapperGeneration(10)]
    [MonoPInvokeCallback(typeof(LuaFunction))]
    public static int LuaCallback(IntPtr luaState)
    {
        return 0;
    }

**Comment by ProgramForFun** [comment]
我之前误会了，以为是下面函数的原型每个都要加这个预留；原来是每个typeof里面的原型加一个就行了，这样只有有数几个需要加；
感谢回复
