### ISSUE TITLE
关于热更程序集的保护

### ISSUE THREAD

**Issue by ProgramForFun** [focus-creative-games/hybridclr#61]
热更程序集不做任何处理的话，用dnspy之类的工具可以直接看到源码；
我们想做一下处理，请问被解释执行的热更程序集，支持https://github.com/obfuscar这类混淆工具做混淆吗？如果支持的话有哪些地方需要特别注意保留不做混淆吗？

**Comment by ProgramForFun** [comment]
如果不支持就只能对程序集整体做对称加密了

**Comment by pirunxi** [comment]
你随便混淆，没问题的
