### ISSUE TITLE
结构体方法调用时候Arm64崩溃

### ISSUE THREAD

**Issue by jackson1991123** [focus-creative-games/hybridclr#63]
**环境：**
Unity 2021.3.21f1c1
HybridCLR版本：v2.2.0
il2cpp_plus版本：v2021-2.2.0
OS+Build：Android OS10 API-29 ABI-ARM64（小米8）
**问题：**
此问题只有ARM64 MethodBridge上有问题，所提供的crashdemo工程必现问题。
此问题在Win64（MethodBridge_Universal64）；Android32（MethodBridge_Universal32）均不出现，因此推断是Interpreter.Execute中的函数签名与MethodBridge中函数签名不一致导致的Crash。这仅仅是推测，希望不要误导开发者。
**问题工程：**
请直接打开上传的包裹，找到Assets/AOTScripts/test2/Entry.cs查看具体情况：
代码片段以及问题注解如下所示
/// <summary>
/// 这个脚本是热更新过后场景的入口
/// EntryAwake时，已经确保HCLR加载完毕
/// Entry.cs是AOT
/// </summary>
public class Entry : MonoBehaviour
{
    private void Awake()
    {
        //AOTStruct是一个只有一个float字段的结构体
        //AOTMethodPvdStruct是一个有函数的结构体，我们调用了这个函数方法导致崩溃

        ///这两行代码很重要，我们确保了AOTMethodPvdStruct<AOTStruct>(xxxxx)方法被il2cpp处理生成了代码
        ///也就是不需要元数据补充这个函数
        ///Tip:如果纯元数据补充，那么不会崩溃
        var pvd = new AOTMethodPvdStruct();
        pvd.Call(Vector2.one, new AOTStruct());
    }

    public void OnClickBug() 
    {
        //这个prefab上贴有BugScript.cs脚本
        //BugScript.cs是个热更新脚本
        //具体详情请跳转到BugScript.cs中进行查看
        var bugPrefab = YooAssets.LoadAssetSync<GameObject>("bug");

        Instantiate(bugPrefab.GetAssetObject<GameObject>());
    }
}

**操作步骤：（请按照步骤统一操作，方便问题顺利复现）**
1 使用对应版本的编辑器打开工程，更新HCLR到指定版本，运行一下游戏，让Unity生成各种dll
2 使用HCLR提供的Generate/All初次编译工程，获得相关dll
3 使用Assets/Arm64.buildconfiguration来初次编译工程（选中这个东西，右上角有个Build，这是Unity整的新花活）
4 再次使用HCLR提供的Generate/All来编译工程，这时候获得了与步骤3所得dll对应的MethodBridge
5 使用YooAssets/AssetBundle Build 界面的ForceBuild选项，确认CopyBuildinFileOption是ClearAndCopyAll，点击构建
6 重复步骤3，得到真正能跑的包 BugRepo.apk（路径在/../Assets/Builds/Arm64文件夹下
7 耐心等待APK安装，直到屏幕中央出现一个雪白的大按钮，点击按钮即可崩溃

**崩溃最小工程**
[BugRepo.zip](https://github.com/focus-creative-games/hybridclr/files/11409153/BugRepo.zip)

**Comment by jackson1991123** [comment]
[BugRepo.zip](https://github.com/focus-creative-games/hybridclr/files/11409151/BugRepo.zip)

**Comment by pirunxi** [comment]
此bug已修复。过段时间会发布。
