### ISSUE TITLE
安卓真机BoxCollider2D无法触发OnMouseEnter等事件

### ISSUE THREAD

**Issue by XuWanXXX** [focus-creative-games/hybridclr#64]
**环境**
Unity 2021.3.1
Win 11
Android 64
HybridCLR 2.3.1

**问题描述**
使用HybridCLRTrail示例项目在安卓真机上，挂载BoxCollider2D的组件无法正常触发OnMouseEnter等事件，同时打包Win64是正常触发的，不安装HybridCLR的普通Unity项目安卓真机也是可以正常触发的。

`private void OnMouseEnter()
    {
        Debug.Log("BoxCollider2D检测到鼠标进入");
    }`
`private void OnMouseUpAsButton()
    {
        Debug.Log("BoxCollider2D检测到鼠标点击");
    }`

**复现方法**
使用提供的最小工程包（在Trail基础上给HotUpdatePrefab加了BoxCollider2D，同时代码增加了OnMouseEnter事件），安装完HybridCLR然后Generate All之后直接打包安卓，进去有个黑色图片，点击无法看到Log。（打包Win64的话可以正常看到点击Log）

**最小工程文件**

[hybridclr_trial-main.zip](https://github.com/focus-creative-games/hybridclr/files/11411737/hybridclr_trial-main.zip)

**Comment by pirunxi** [comment]
这是被裁剪导致脚本missing引起。 这个功能如此常用，是不可能有问题的。

**Comment by wcytian** [comment]
那要如何解决这个问题，手动在link.xml保留相关函数吗
