### ISSUE TITLE
DHE版本中，GenericMethod::CreateMethodLocked可能找不到存在的AOT函数

### ISSUE THREAD

**Issue by AlanLiu90** [focus-creative-games/hybridclr#65]
对于DHE Assembly，`methodDefinition`的token可能和原始Assembly的不一致，导致`MetadataCache::GetMethodPointer`无法查找到AOT函数，从而执行到了后面的获取解释器函数的分支。看起来，应该类似`gmethod->context`那样，尝试将`methodDefinition`转成原始Assembly对应的`methodDefinition`？

**Comment by pirunxi** [comment]
我们会尽快处理这个问题

**Comment by pirunxi** [comment]
我看这个逻辑处理是正常的，会被判定为解释器函数，跳转到InterpreterModule::GetMethodPointer，再检查是dhe函数，再被转换。

**Comment by pirunxi** [comment]
我们再检查一下

**Comment by pirunxi** [comment]
确定是有问题的，而且是非常严重的bug，我们马上解决

**Comment by pirunxi** [comment]
已经解决这个问题。QQ上沟通。
