### ISSUE TITLE
I have got this error when the script executing `Assembly.Load(bytes)`  method. I'm crying.

### ISSUE THREAD

**Issue by pfzsteven** [focus-creative-games/hybridclr#67]
[19:15:40]NotSupportedException: /Applications/Unity/Hub/Editor/2020.3.15f2c1/2021.3.6f1c1/Unity.app/Contents/il2cpp/libil2cpp/icalls/mscorlib/System/AppDomain.cpp(168) : Unsupported internal call for IL2CPP:AppDomain::LoadAssemblyRaw - "This icall is not supported by il2cpp."
[19:15:40]stacktrace:
System.AppDomain.LoadAssemblyRaw (System.Byte[] rawAssembly, System.Byte[] rawSymbolStore, System.Security.Policy.Evidence securityEvidence, System.Boolean refonly) (at <00000000000000000000000000000000>:0)
System.AppDomain.Load (System.Byte[] rawAssembly, System.Byte[] rawSymbolStore, System.Security.Policy.Evidence securityEvidence, System.Boolean refonly) (at <00000000000000000000000000000000>:0)
System.AppDomain.Load (System.Byte[] rawAssembly, System.Byte[] rawSymbolStore, System.Security.Policy.Evidence securityEvidence) (at <00000000000000000000000000000000>:0)
System.AppDomain.Load (System.Byte[] rawAssembly) (at <00000000000000000000000000000000>:0)
System.Reflection.Assembly.Load (System.Byte[] rawAssembly) (at <00000000000000000000000000000000>:0)

**Comment by pirunxi** [comment]
Unity uses precompiled libil2cpp.a when you export xcode project for ios target.  The origin libil2cpp.a doesn't contains any hybridclr code so you will see the error. You should compile custom libil2cpp.a and replace corresponding one in xcode project.  you can read [this document](https://hybridclr.doc.code-philosophy.com/#/basic/buildpipeline) for compiling libil2cpp.a .
