### ISSUE TITLE
HybridCLR设计架构图？

### ISSUE THREAD

**Issue by wjf1616** [focus-creative-games/hybridclr#68]
通过对HybridCLR理解和测试，画了个架构图，不知道对不对？
![HybridCLR架构图](https://github.com/focus-creative-games/hybridclr/assets/16534485/99184e41-960e-4725-8a84-f03c68190ff5)

官方能否出个详细的架构图，便于学习和理解

**Comment by pirunxi** [comment]
你这个图没什么问题。大结构来说，README里 ![这张图](https://github.com/focus-creative-games/hybridclr/raw/main/docs/images/architecture.png) 说得挺清楚的。 文档里也附带几篇文章讲[实现原理](https://hybridclr.doc.code-philosophy.com/#/blog/principle)的。

**Comment by wjf1616** [comment]
你的邮件我已经收到，谢谢，以后常联系！
