### ISSUE TITLE
不支持Unity2022.3LTS Android平台

### ISSUE THREAD

**Issue by sunsvip** [focus-creative-games/hybridclr#71]
多台电脑实测，最新版HybridCLR在Unity2022.3LTS下Windows平台可以打出包，打Android平台报了很多il2cpp的编译错误。复现方法：新建工程->安装HybridCLR->打包安卓

**Comment by sunsvip** [comment]
哦，明白了。应该是取消了ARMv7的支持，只勾选ARM64正常出包

**Comment by pirunxi** [comment]
支持，与WenGL是相同的问题。下个版本会修复。
