### ISSUE TITLE
升级3.1.0版本后，运行出现il2cpp不存在的代码，是需要做什么修改吗。使用2.4.2版本没什么问题

### ISSUE THREAD

**Issue by xhaoh94** [focus-creative-games/hybridclr#72]
![Uploading Snipaste_2023-06-13_20-59-50.png…]()

**Comment by xhaoh94** [comment]
![Snipaste_2023-06-13_20-59-50](https://github.com/focus-creative-games/hybridclr/assets/30614075/15f4a0eb-97ec-4716-b87e-a81c3f471ebe)

**Comment by pirunxi** [comment]
升级到3.1.1，如果还有问题，按照bug反馈文档要求发给我们

**Comment by xhaoh94** [comment]
Unity Editor版本: 2022.3.1f1。
操作系统: Win 10。
BuildTarget: PC。
com.code-philosophy.hybridclr的版本号:v3.1.1。
hybridclr仓库的版本号:v3.1.1。
il2cpp_plus仓库的版本号:v2022-3.0.2。
截图及日志文件
复现条件：启动后，进入热更必现
复现项目 https://github.com/xhaoh94/UxGame.git
打开工程后，在菜单栏 UxGame->构建->构建打包，把构建类型修改为ForceRebuild.然后直接打包即可
打包程序在工程的Release目录下
打包后，菜单栏 UxGame->构建->本地资源服务器.
启动后，进去程序加载完热更资源后，进入热更场景后，就会出现上面的报错

**Comment by pirunxi** [comment]
请严格按照 文档要求给出测试用例。这样的用例会让我们浪费太多时间在熟悉你们的打包方式。

**Comment by pirunxi** [comment]
这个问题我们已经修复。下个版本会放出。有问题及时反馈

**Comment by xhaoh94** [comment]
辛苦了




xhaoh94
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "focus-creative-games/hybridclr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [focus-creative-games/hybridclr] 升级3.1.0版本后，运行出现il2cpp不存在的代码，是需要做什么修改吗。使用2.4.2版本没什么问题 (Issue #72)





 
这个问题我们已经修复。下个版本会放出。有问题及时反馈
