### ISSUE TITLE
升级到3.1.1后，报 Could not load type from assembly的错误

### ISSUE THREAD

**Issue by song428** [focus-creative-games/hybridclr#73]
在调用 LoadMetadataForAOTAssembly后，使用LoadAssembly依次加载热更程序集时出现
TypeLoadException: Could not load type 'SeekList`2' from assembly 'mscorlib 的错误，
奇怪的是这是一个热更程序集中并没有被用到的类
定义如下：
```
public class SeekList<TK, TV> : IDictionary<TK, TV>, IReadOnlyDictionary<TK, TV> where TK : notnull
{
        TK[] _arr;
        readonly Dictionary<TK, TV> _dic;
        readonly IComparer<TK> _comparer;
        int _size;

        public SeekList(int capacity = 4, IComparer<TK> comparer = null)
        {
            _arr = new TK[capacity];
            _dic = new Dictionary<TK, TV>(capacity);
            _comparer = comparer ?? Comparer<TK>.Default;
            _size = 0;
        }
}
```
我尝试在主程序集中添加了Dictionary的相关的调用，link.xml也添加了Dictionary还是无法解决，回退到老版本2.1.0就可以

**Comment by pirunxi** [comment]
请提供信息给我们，才能快速解决

**Comment by song428** [comment]
麻烦下看

断点的执行路径是：
![image](https://github.com/focus-creative-games/hybridclr/assets/32450437/3476b79e-facf-415f-a632-9a7171d5118f)

在resolve_parse_info_internal，需要返回kclass，整个函数走完也没有找到它，然后返回NULL导致的异常

**Comment by pirunxi** [comment]
已解决，升级到3.2.0

**Comment by song428** [comment]
升级后，还是存在这问题

**Comment by song428** [comment]
[hybridclr_trial-main.zip](https://github.com/focus-creative-games/hybridclr/files/11779616/hybridclr_trial-main.zip)

麻烦有空看看，使用的测试工程升级到3.2.0，在hotUpdate程序集中，添加了对应的类型，打包出来后，会有上面反馈的错误

**Comment by pirunxi** [comment]
验证确实有bug。不过原因在于3.x版本起调用了il2cpp TypeNameParser，它的实现实现有bug。我们已修复，下个版本会放出。

**Comment by song428** [comment]
好的好的，辛苦了
