### ISSUE TITLE
Exception: resolve AOT dll:netstandard 失败

### ISSUE THREAD

**Issue by listentowindy** [focus-creative-games/hybridclr#76]
Unity Editor版本：2021.3.16f1c1
操作系统: Windows 11, 22H2
出错的BuildTarget: Win64
com.code-philosophy.hybridclr的版本号: 3.2.0
hybridclr仓库的版本号: 3.1.2
il2cpp_plus仓库的版本号: v2021-3.0.2

问题： 运行Generate/All后报错, “Exception: resolve AOT dll:netstandard 失败! 请确保主工程已经引用了该dll并且正确生成了裁剪后的AOT dll。更多请参阅常见错误文档”
![image](https://github.com/focus-creative-games/hybridclr/assets/6919440/08624a90-45b1-4d49-9cc5-447826cb0c23)

现象：把Assembly-CSharp加入到HotUpdateAssemblies配置后，会失败；如果没有加入，能正常编译。
已经做了这些工作，但没有效果：
 1. 确认PlayerSettings的Api Compatability Level 已经设置为 .Net Framework
 2. 把Generated/AOTGenericReferences.cs的“AOT generic types” 加入到 AOT代码中，PatchedAOTAssemblyList加入到PatchedAOTAssemblies配置中
 3. 确认AOT代码(LoadDll)定义为程序集，并且没有加入到热更新列表中
 
![image](https://github.com/focus-creative-games/hybridclr/assets/6919440/6eeca66b-b3dc-414d-baad-7de095eb4af4)

这个问题要怎么解决呢？

**Comment by listentowindy** [comment]
重新打包不能解决，如果第三方dll使用了netstandard，那要怎么处理呢

**Comment by LuHec** [comment]
AOT不能直接用热更的类型
