### ISSUE TITLE
如何解决第三方包依赖netstandard的问题

### ISSUE THREAD

**Issue by listentowindy** [focus-creative-games/hybridclr#78]
第三方包使用了netstandard，导致Generate/All的时候失败，“Exception: resolve AOT dll:netstandard 失败! 请确保主工程已经引用了该dll并且正确生成了裁剪后的AOT dll。更多请参阅常见错误文档”。
PlayerSettings的Api Compatability Level 已经设置为 .Net Framework。

请问当第三方包依赖netstandard时，要怎么处理？

Unity Editor版本：2021.3.16
操作系统: Windows 11
出错的BuildTarget: Win64
com.code-philosophy.hybridclr的版本号: 3.2.0
hybridclr仓库的版本号: 3.1.2
il2cpp_plus仓库的版本号: v2021-3.0.2

**Comment by pirunxi** [comment]
这个只影响generate ，不影响打包后运行。 你要么将dll换成.net 45，要么自行修改generate的代码解决这个问题。
