### ISSUE TITLE
手机上崩溃时无法解析HybridCLR的调用堆栈

### ISSUE THREAD

**Issue by qfc123** [focus-creative-games/hybridclr#84]
手机上崩溃时无法解析HybridCLR的调用堆栈，有什么办法能解析吗？或者有什么替代方案？否则线上崩溃很难查找原因。

**Comment by qfc123** [comment]
示例项目也无法解析到崩溃信息，无法找到导致崩溃的函数

**Comment by pirunxi** [comment]
就如lua崩溃时你也不可能能获得lua解释栈一样，hybridclr崩溃时，你也无法获得调用堆栈。除非你在崩溃的时候，还有机会执行一些清理代码，此时你可以在清理代码中查询获得hybridclr当前的执行栈信息。

**Comment by qfc123** [comment]
bugly能获取到堆栈，但是获取不到关键的那几行
![img_v2_258468f3-106c-4d50-b408-7abaa833776g](https://github.com/focus-creative-games/hybridclr/assets/25084033/3c8aecbd-f938-44a4-9752-9c9fce35b4b8)
