### ISSUE TITLE
请问这个新版huatuo和hybridclr是什么关系？为什么内容一模一样？

### ISSUE THREAD

**Issue by weimingjue** [focus-creative-games/hybridclr#85]
我很纳闷，为什么两个项目内容一模一样
https://github.com/focus-creative-games/hybridclr
https://github.com/tuyoogame/huatuo

**Comment by pirunxi** [comment]
huatuo是hybridclr的前身，这个也是我们写的。后面我们独立成新公司后，重新开了新的项目叫hybridclr。huatuo属于之前的公司，这个仓库已经不维护了。

**Comment by weimingjue** [comment]
好吧，应该明白你的意思了
