### ISSUE TITLE
就如lua崩溃时你也不可能能获得lua解释栈一样，hybridclr崩溃时，你也无法获得调用堆栈。除非你在崩溃的时候，还有机会执行一些清理代码，此时你可以在清理代码中查询获得hybridclr当前的执行栈信息。

### ISSUE THREAD

**Issue by qfc123** [focus-creative-games/hybridclr#86]
就如lua崩溃时你也不可能能获得lua解释栈一样，hybridclr崩溃时，你也无法获得调用堆栈。除非你在崩溃的时候，还有机会执行一些清理代码，此时你可以在清理代码中查询获得hybridclr当前的执行栈信息。

_Originally posted by @pirunxi in https://github.com/focus-creative-games/hybridclr/issues/84#issuecomment-1614500758_

**Comment by qfc123** [comment]
bugly能获取到堆栈
![img_v2_4df4071a-2b9e-4a69-a8fd-cd81e6c6d0fg](https://github.com/focus-creative-games/hybridclr/assets/25084033/83ad6a0d-af78-4d9d-bafb-e20e342dd3e8)
但是缺少最关键的几行，只解析到了套的壳子，不能具体到具体的函数名、行数

**Comment by qfc123** [comment]
期望能有解析堆栈的方法，比如提供程序集

**Comment by pirunxi** [comment]
我意思是，系统默认可以获得原生栈，但这种解释器栈是得不到的。除非你在崩溃的时候还能执行一些扫尾代码，此时可以调用hybridclr的接口获得解释器栈。

**Comment by yeamour** [comment]
我们也遇到了同样的问题。 app崩溃时，能否执行扫尾代码，这真的很难说。能通过守护进程去做这个扫尾工作吗？

**Comment by qfc123** [comment]
> 我意思是，系统默认可以获得原生栈，但这种解释器栈是得不到的。除非你在崩溃的时候还能执行一些扫尾代码，此时可以调用hybridclr的接口获得解释器栈。
看到介绍里有不少上线项目，有例子说明怎么让线上崩溃率达标吗？ 从目前的情况来看，如果崩溃时执行不了扫尾代码，那只能看着崩溃率干着急了？

**Comment by pirunxi** [comment]
现在已经很稳定了。就算有崩溃也是非hybridclr引起的。所以那些上线项目并不会为hybridclr这个问题而苦恼，凑合着吧。

**Comment by qfc123** [comment]
> 现在已经很稳定了。就算有崩溃也是非hybridclr引起的。所以那些上线项目并不会为hybridclr这个问题而苦恼，凑合着吧。

嗯，可能我没表述清楚问题， 不是专指hybridclr框架导致的崩溃，是指所有的崩溃，项目要上线的话有崩溃率指标，未使用hybridclr框架时，用bugly能统计到详细崩溃堆栈，定位到问题函数和行数，使用后只统计到了下图所示这一层，看起来是hybridclr包的那层壳子。  在想这个问题，目前分析的猜测是 HybridCLR为了热更包了一层壳子，堆栈记录是有上限的，尤其这种多线程，封装多，可能堆栈打不全
![image](https://github.com/focus-creative-games/hybridclr/assets/25084033/010eb8e3-c126-448a-a2fb-d009f1711721)

**Comment by qfc123** [comment]
> bugly能获取到堆栈 ![img_v2_4df4071a-2b9e-4a69-a8fd-cd81e6c6d0fg](https://user-images.githubusercontent.com/25084033/250424380-83ad6a0d-af78-4d9d-bafb-e20e342dd3e8.png) 但是缺少最关键的几行，只解析到了套的壳子，不能具体到具体的函数名、行数

到了这一层就断掉了，还缺少最关键的3行。
