### ISSUE TITLE
我们也遇到了同样的问题。 app崩溃时，能否执行扫尾代码，这真的很难说。能通过守护进程去做这个扫尾工作吗？

### ISSUE THREAD

**Issue by yeamour** [focus-creative-games/hybridclr#87]
我们也遇到了同样的问题。 app崩溃时，能否执行扫尾代码，这真的很难说。能通过守护进程去做这个扫尾工作吗？

_Originally posted by @yeamour in https://github.com/focus-creative-games/hybridclr/issues/86#issuecomment-1617196377_

**Comment by pirunxi** [comment]
如果能dump crash 文件，能调试执行栈和相关数据的话，倒是有机会分析一下栈。 解释器栈的问题，所有解释语言都类似，像lua如果崩溃了，也是无法获得解释代码栈的。
