### ISSUE TITLE
bugly能获取到崩溃堆栈但是缺少最关键的几行，只解析到了套的壳子，不能具体到具体的函数名、行数，这个有什么思路吗？

### ISSUE THREAD

**Issue by qfc123** [focus-creative-games/hybridclr#89]
> bugly能获取到堆栈 ![img_v2_4df4071a-2b9e-4a69-a8fd-cd81e6c6d0fg](https://user-images.githubusercontent.com/25084033/250424380-83ad6a0d-af78-4d9d-bafb-e20e342dd3e8.png) 但是缺少最关键的几行，只解析到了套的壳子，不能具体到具体的函数名、行数

到了这一层就断掉了，还缺少最关键的3行。

_Originally posted by @qfc123 in https://github.com/focus-creative-games/hybridclr/issues/86#issuecomment-1617513472_

**Comment by qfc123** [comment]
![image](https://github.com/focus-creative-games/hybridclr/assets/25084033/4bc832f7-f98f-422f-a5da-416424be772d)

**Comment by qfc123** [comment]
> ![image](https://user-images.githubusercontent.com/25084033/250510719-4bc832f7-f98f-422f-a5da-416424be772d.png)

目前有个怀疑 HybridCLR为了热更包了一层壳子，堆栈记录是有上限的，尤其这种多线程，封装多，可能堆栈打不全

**Comment by pirunxi** [comment]
后面再研究研究。
