### ISSUE TITLE
热更Assembly-CSharp.dll中，函数添加[BurstCompile]属性，MethodBridge报错

### ISSUE THREAD

**Issue by leelnfei** [focus-creative-games/hybridclr#91]
unity:2022.3.4f1
hybridclr:3.3.0
Build Settings中Api Compatible Level是.Net Framework
新建任意脚本，添加任意函数，在新加的函数上添加[BurstCompile]，执行MethodBridge，然后会抛出异常Exception: resolve AOT dll:mscorlib 失败! 请确保主工程已经引用了该dll并且正确生成了裁剪后的AOT dll。
在函数上添加[BurstCompile]是正确的，只有函数添加[BurstCompile]就会抛出异常

**Comment by BUGyyc** [comment]
how to do?

**Comment by BUGyyc** [comment]
跟我遇到的问题类似，要怎么解决？

**Comment by pirunxi** [comment]
我们现在已经解决了这个问题。商业化版本已经支持绝大多数dots特性，具体见 https://hybridclr.doc.code-philosophy.com/docs/business/dots
