### ISSUE TITLE
群中提问被移出了群聊

### ISSUE THREAD

**Issue by playg8** [focus-creative-games/hybridclr#94]
这个框架在我看来问题多多，配置时候经常出现莫名其妙的错误。今日在mac上进行了一次项目迁移。然后出错了，在群中贴出报错截图。群里回答只有一句话，看文档。只要你有问题就说你没有看文档，或者没有认真看文档。我相信大家肯定有和我一样的情况，总是莫名其妙的会出现 一些配置上的错误或者上使用上不明白的地方需要群里和大家交流。
但是当你交流时候，难道不能 有一点不同意见？有不同意见就把你移出群聊，这是什么意思？
文档和代码缺陷既然暴露出来了，进行更新改进或者提供解决方案不好？把自己当大爷了啊，有bug有问题也不允许别人提了？逃避不是解决问题的办法。
面对不同框架的选择，作者的负责人程度是很重要的，不然一旦项目遇到致命问题，需要帮助时候，则对项目极为不利，特别是使用一种不成熟框架时候。
看群里作者回答别人问题时候，也就只会说这不是框架问题，看文档，仔细看文档。这么说吧，要是文档里面能查到，何必去群里问？而且看群主回答问题时候，语气都显得很不耐烦，这让我也对这个框架没有了期待。
网上搜索热更方案时候，见到好多人夸这个框架多好多好，我倒是有不同 意见，那些看起来像是水军发言。实际体验并没有很好。

**Comment by playg8** [comment]
呵呵，群众的眼睛是雪亮的

**Comment by yingran-cn** [comment]
确实，这个公司的人品特差！！！！！！老子用ts了。傻逼玩意
