### ISSUE TITLE
按照新手教程中的快速上手时闪退

### ISSUE THREAD

**Issue by dh224** [focus-creative-games/hybridclr#95]
- Unity Editor版本。 2021.3.27。
- 操作系统。 Win 10。
- 出错的BuildTarget.   Windows。
- com.code-philosophy.hybridclr的版本号。v3.4.0。
- hybridclr仓库的版本号。v3.4.0。
- il2cpp_plus仓库的版本号。如v2021-2.2.0。?这是什么东西
- 截图及日志文件
Build时没报错，运行exe文件时闪退。
![图片1](https://github.com/focus-creative-games/hybridclr/assets/24605350/bb7d2d31-0d0c-4982-a7cc-f98b4c1fb9cb)
![图片2](https://github.com/focus-creative-games/hybridclr/assets/24605350/e8c7fe94-f9a1-4496-833c-2edde84115ac)

- 复现条件
运行Build后的exe

**Comment by pirunxi** [comment]
发给我们检查一下，但不太可能是我们的问题。
