### ISSUE TITLE
iOS unity 2020.3.40使用hybrid v2.4.2，热更大量MonoBehaviour有概率闪退，android没此问题，将这些MonoBehaviour移出热更范畴后，闪退消失

### ISSUE THREAD

**Issue by NewbieGameCoder** [focus-creative-games/hybridclr#96]
堆栈如下，目前有3万iOS玩家受到了影响

已崩溃：com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000117d9cd28
0
UnityFramework
hash_set.h - 第 981 行
core::hash_set<core::pair<long const, MonoScriptCache*, false>, core::hash_pair<core::hash<long>, long const, MonoScriptCache*>, core::equal_pair<std::__1::equal_to<long>, long const, MonoScriptCache*>>::node* core::hash_set<core::pair<long const, MonoScriptCache*, false>, core::hash_pair<core::hash<long>, long const, MonoScriptCache*>, core::equal_pair<std::__1::equal_to<long>, long const, MonoScriptCache*>>::lookup<long, core::equal_pair<std::__1::equal_to<long>, long const, MonoScriptCache*>>(long const&, core::equal_pair<std::__1::equal_to<long>, long const, MonoScriptCache*> const&) const + 981
1
UnityFramework
hash_map.h - 第 166 行
core::hash_map<long, MonoScriptCache*, core::hash<long>, std::__1::equal_to<long>>::find(long const&) + 166
2
UnityFramework
hash_set.h - 第 379 行
ScriptingManager::GetMonoScriptCache(long) + 379
3
UnityFramework
MonoScriptCache.cpp - 第 641 行
FindOrCreateMonoScriptCache(ScriptingClassPtr, InitScriptingCacheType, Object*, int) + 641
4
UnityFramework
SerializableManagedRef.cpp - 第 176 行
SerializableManagedRef::SetupScriptingCache(Object*, ScriptingClassPtr, MonoScript*) + 176
5
UnityFramework
SerializableManagedRef.cpp - 第 194 行
SerializableManagedRef::RebuildMonoInstance(Object*, ScriptingClassPtr, ScriptingObjectPtr, MonoScript*) + 194
6
UnityFramework
SerializableManagedRef.cpp - 第 250 行
SerializableManagedRef::RebuildMonoInstanceFromScriptChange(Object*, ScriptingClassPtr, ScriptingObjectPtr) + 250
7
UnityFramework
Behaviour.h - 第 28 行
ManagedMonoBehaviourRef::RebuildMonoInstanceFromScriptChange(Object*, ScriptingClassPtr, ScriptingObjectPtr) + 28
8
UnityFramework
SerializableManagedRef.cpp - 第 372 行
SerializableManagedRef::SetScript(Object*, PPtr<MonoScript>, ScriptingObjectPtr) + 372
9
UnityFramework
CloneObject.cpp - 第 41 行
ProduceClone(Object&) + 41
10
UnityFramework
CloneObject.cpp - 第 65 行
CollectAndProduceGameObjectHierarchy(Transform&, Transform*, vector_map<int, int, std::__1::less<int>, stl_allocator<std::__1::pair<int, int>, (MemLabelIdentifier)1, 16>>&) + 65
11
UnityFramework
CloneObject.cpp - 第 211 行
CollectAndProduceClonedIsland(Object&, Transform*, vector_map<int, int, std::__1::less<int>, stl_allocator<std::__1::pair<int, int>, (MemLabelIdentifier)1, 16>>&) + 211
12
UnityFramework
BlockMemoryCacheWriter.h - 第 38 行
CloneObjectImpl(Object*, Transform*, vector_map<int, int, std::__1::less<int>, stl_allocator<std::__1::pair<int, int>, (MemLabelIdentifier)1, 16>>&) + 38
13
UnityFramework
CloneObject.cpp - 第 394 行
CloneObject(Object&, Transform&, bool) + 394
14
UnityFramework
UnityObjectMarshalling.h - 第 211 行
Object_CUSTOM_Internal_CloneSingleWithParent(ScriptingBackendNativeObjectPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*, unsigned char) + 211
15
UnityFramework
sparsehashtable.h - 第 929 行
google::sparse_hashtable<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>, KeyWrapper<il2cpp::vm::InternedString>, il2cpp::vm::InternedStringHash, google::sparse_hash_map<KeyWrapper<il2cpp::vm::InternedString>, unsigned long, il2cpp::vm::InternedStringHash, KeyWrapper<il2cpp::vm::InternedString>::EqualsComparer<il2cpp::vm::InternedStringCompare>, google::libc_allocator_with_realloc<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>>>::SelectKey, google::sparse_hash_map<KeyWrapper<il2cpp::vm::InternedString>, unsigned long, il2cpp::vm::InternedStringHash, KeyWrapper<il2cpp::vm::InternedString>::EqualsComparer<il2cpp::vm::InternedStringCompare>, google::libc_allocator_with_realloc<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>>>::SetKey, KeyWrapper<il2cpp::vm::InternedString>::EqualsComparer<il2cpp::vm::InternedStringCompare>, google::libc_allocator_with_realloc<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>>>::insert_at(std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long> const&, unsigned long) (.cold.2) + 929
16
UnityFramework
sparsehashtable.h - 第 929 行
google::sparse_hashtable<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>, KeyWrapper<il2cpp::vm::InternedString>, il2cpp::vm::InternedStringHash, google::sparse_hash_map<KeyWrapper<il2cpp::vm::InternedString>, unsigned long, il2cpp::vm::InternedStringHash, KeyWrapper<il2cpp::vm::InternedString>::EqualsComparer<il2cpp::vm::InternedStringCompare>, google::libc_allocator_with_realloc<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>>>::SelectKey, google::sparse_hash_map<KeyWrapper<il2cpp::vm::InternedString>, unsigned long, il2cpp::vm::InternedStringHash, KeyWrapper<il2cpp::vm::InternedString>::EqualsComparer<il2cpp::vm::InternedStringCompare>, google::libc_allocator_with_realloc<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>>>::SetKey, KeyWrapper<il2cpp::vm::InternedString>::EqualsComparer<il2cpp::vm::InternedStringCompare>, google::libc_allocator_with_realloc<std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long>>>::insert_at(std::__1::pair<KeyWrapper<il2cpp::vm::InternedString> const, unsigned long> const&, unsigned long) (.cold.2) + 929
17
UnityFramework
MethodBridge_Arm64.cpp - 第 8647 行
__M2N_i8i8i8u1(MethodInfo const*, unsigned short*, hybridclr::interpreter::StackObject*, void*) + 8647
18
UnityFramework
Interpreter_Execute.cpp - 第 4810 行
hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*) + 4810
19
UnityFramework
MethodBridge_Arm64.cpp - 第 45376 行
__N2M_vi8i8(long long, long long, MethodInfo const*) + 45376

**Comment by pirunxi** [comment]
这是我们首次遇到这样的问题，由于android与ios使用完全相同的代码，不确定是否是使用失误引起还是ios平台独有的问题。 请联系我们的商业技术支持，配合解决此问题。

**Comment by AlanLiu90** [comment]
之前排查这个问题的时候，以为只有`AddComponent`会引发崩溃，最近发现`Destroy`也会引发这类崩溃。我实现了[一个库](https://github.com/AlanLiu90/HybridCLRCrashWorkarounds)规避这个问题，效率比直接对所有`MonoBehaviour`调用一次`AddComponent`要高。在我们项目中集成后，确认这类崩溃消失了。

**Comment by AntaresZ** [comment]
这个issues为啥关了啊，我也碰到这个崩溃了
Unity 2022.3.62f3
HybridCLR 8.8.0

堆栈

Exception Category: mach
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000154cf2bb0
Crashed Thread:  0
CrashDoctor Diagnosis: Attempted to dereference garbage pointer 0x154cf2bb0.
Originated at or in a subcall of _0a683484ef7d482a246041cb6488b3a2o
Thread 0 Crashed:
0   UnityFramework                      0x000000010bcb603c lookup<long, core::equal_pair<std::equal_to<long>, long, std::weak_ptr<MonoScriptCache> > > + [hash_set.h : 948]
1   UnityFramework                      0x000000010bcb6028 lookup<long, core::equal_pair<std::equal_to<long>, long, std::weak_ptr<MonoScriptCache> > > + [hash_set.h : 942]
2   UnityFramework                      0x000000010bcb3a70 GetMonoScriptCache + [ScriptingManager.cpp : 266]
3   UnityFramework                      0x000000010bcc64f0 FindOrCreateMonoScriptCache + [MonoScriptCache.cpp : 629]
4   UnityFramework                      0x000000010bd054f0 SetupScriptingCache + [memory : 3148]
5   UnityFramework                      0x000000010bd0586c RebuildMonoInstance + [SerializableManagedRef.cpp : 219]
6   UnityFramework                      0x000000010bd05e8c RebuildMonoInstanceFromScriptChange + [SerializableManagedRef.cpp : 288]
7   UnityFramework                      0x000000010bcc2d6c RebuildMonoInstanceFromScriptChange + [Behaviour.h : 28]
8   UnityFramework                      0x000000010bd064d8 SetScript + [SerializableManagedRef.cpp : 419]
9   UnityFramework                      0x000000010bd062d8 SetScriptingDataFrom + [SerializableManagedRef.cpp : 348]
10  UnityFramework                      0x000000010ba99f94 ProduceClone + [CloneObject.cpp : 65]
11  UnityFramework                      0x000000010ba97af4 CollectAndProduceGameObjectHierarchy + [CloneObject.cpp : 0]
12  UnityFramework                      0x000000010ba9777c CollectAndProduceClonedIsland + [CloneObject.cpp : 0]
13  UnityFramework                      0x000000010ba98ae0 CloneObjectImpl + [CloneObject.cpp : 307]
14  UnityFramework                      0x000000010ba99014 CloneObject + [CloneObject.cpp : 554]
15  UnityFramework                      0x000000010b911ee8 Object_CUSTOM_Internal_CloneSingleWithParent + [UnityObjectMarshalling.h : 211]
16  UnityFramework                      0x000000010f11ddc0 Object_Instantiate_m99F2A72EF6BFE09E6CF4FCF6207C5BCFAD1D76CF + [UnityEngine.CoreModule__4.cpp : 27721]
17  UnityFramework                      0x000000010d541d8c Object_Instantiate_TisRuntimeObject_mDC5AD8BD13FE50E98B67B956C048367F4E8C6F94_gshared + [GenericMethods__23.cpp : 13752]
18  UnityFramework                      0x000000010cfbbc1c __M2N_uuuu1(MethodInfo const*, unsigned short*, hybridclr::interpreter::StackObject*, void*) + [MethodBridge.cpp : 72024]
19  UnityFramework                      0x000000010ce23f04 hybridclr::interpreter::Interpreter::Execute(MethodInfo const*, hybridclr::interpreter::StackObject*, void*) + [Interpreter_Execute.cpp : 4987]
20  UnityFramework                      0x000000010ce2ab34 hybridclr::interpreter::InterpreterInvoke(void (*)(), MethodInfo const*, void*, void**, void*) + [InterpreterModule.cpp : 0]
21  UnityFramework                      0x000000010ce576c8 il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) + [Runtime.cpp : 0]
22  UnityFramework                      0x000000010ce575ec il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + [Runtime.cpp : 606]
23  UnityFramework                      0x000000010bcadba8 scripting_method_invoke + [ScriptingApi_Il2Cpp.cpp : 290]
24  UnityFramework                      0x000000010bcba2f8 Invoke + [ScriptingInvocation.cpp : 298]
25  UnityFramework                      0x000000010bcc3ecc CallUpdateMethod + [MonoBehaviour.cpp : 594]
26  UnityFramework                      0x000000010ba99990 CommonUpdate<BehaviourManager> + [Behaviour.cpp : 180]
27  UnityFramework                      0x000000010bb78360 ExecutePlayerLoop + [PlayerLoop.cpp : 406]
28  UnityFramework                      0x000000010bb783a0 ExecutePlayerLoop + [PlayerLoop.cpp : 430]
29  UnityFramework                      0x000000010bb7869c PlayerLoop + [PlayerLoop.cpp : 540]
30  UnityFramework                      0x000000010c4343cc UnityPlayerLoopImpl + [LibEntryPoint.mm : 352]
31  UnityFramework                      0x000000010b8ad30c UnityRepaint + [UnityAppController+Rendering.mm : 218]
